// Code generated by gen_string_enum.go. DO NOT EDIT.

package LocalizerBundle

import "fmt"

// LocaleKey represents a localization message key as a string enum.
type LocaleKey string

// Define all valid LocaleKey values.
const (
	LocaleKeyAccept                               LocaleKey = "Accept"
	LocaleKeyAlreadyHaveAnAccount                 LocaleKey = "AlreadyHaveAnAccount"
	LocaleKeyBack                                 LocaleKey = "Back"
	LocaleKeyCheckingDotDot                       LocaleKey = "CheckingDotDot"
	LocaleKeyConfirmEmail                         LocaleKey = "ConfirmEmail"
	LocaleKeyConfirmEmailRequired                 LocaleKey = "ConfirmEmailRequired"
	LocaleKeyConfirmPassword                      LocaleKey = "ConfirmPassword"
	LocaleKeyConfirmYourNewPassword               LocaleKey = "ConfirmYourNewPassword"
	LocaleKeyContinue                             LocaleKey = "Continue"
	LocaleKeyCookieConsentStatement               LocaleKey = "CookieConsentStatement"
	LocaleKeyCreateAccount                        LocaleKey = "CreateAccount"
	LocaleKeyCreateOne                            LocaleKey = "CreateOne"
	LocaleKeyDidntReceiveCode                     LocaleKey = "DidntReceiveCode"
	LocaleKeyDontHaveAnAccount                    LocaleKey = "DontHaveAnAccount"
	LocaleKeyEmailAddress                         LocaleKey = "EmailAddress"
	LocaleKeyEmailAlreadyInUse                    LocaleKey = "EmailAlreadyInUse"
	LocaleKeyEmailIsRequired                      LocaleKey = "EmailIsRequired"
	LocaleKeyEmailNotFound                        LocaleKey = "EmailNotFound"
	LocaleKeyEmailsDoNotMatch                     LocaleKey = "EmailsDoNotMatch"
	LocaleKeyEnterEmailToContinue                 LocaleKey = "EnterEmailToContinue"
	LocaleKeyEnterTheVerificationCodeSentToF      LocaleKey = "EnterTheVerificationCodeSentToF"
	LocaleKeyEnterValidEmail                      LocaleKey = "EnterValidEmail"
	LocaleKeyEnterYourEmail                       LocaleKey = "EnterYourEmail"
	LocaleKeyEnterYourEmailToContinue             LocaleKey = "EnterYourEmailToContinue"
	LocaleKeyEnterYourNewPassword                 LocaleKey = "EnterYourNewPassword"
	LocaleKeyEnterYourNewPasswordBelow            LocaleKey = "EnterYourNewPasswordBelow"
	LocaleKeyEnterYourPassword                    LocaleKey = "EnterYourPassword"
	LocaleKeyEnterYourPasswordF                   LocaleKey = "EnterYourPasswordF"
	LocaleKeyEnterYourVerficationCode             LocaleKey = "EnterYourVerficationCode"
	LocaleKeyError                                LocaleKey = "Error"
	LocaleKeyFailedToCreateAcctountF              LocaleKey = "FailedToCreateAcctountF"
	LocaleKeyFailedToLookUpEmailF                 LocaleKey = "FailedToLookUpEmailF"
	LocaleKeyFillInYourDetailsToCreateANewAccount LocaleKey = "FillInYourDetailsToCreateANewAccount"
	LocaleKeyForgotPassword                       LocaleKey = "ForgotPassword"
	LocaleKeyInvalidEmailAddress                  LocaleKey = "InvalidEmailAddress"
	LocaleKeyInvalidPassword                      LocaleKey = "InvalidPassword"
	LocaleKeyInvalidRedirectURL                   LocaleKey = "InvalidRedirectURL"
	LocaleKeyInvalidResponseFromServer            LocaleKey = "InvalidResponseFromServer"
	LocaleKeyInvalidVerificationCode              LocaleKey = "InvalidVerificationCode"
	LocaleKeyKeepMeSignedIn                       LocaleKey = "KeepMeSignedIn"
	LocaleKeyKeepMeSignedInDescription            LocaleKey = "KeepMeSignedInDescription"
	LocaleKeyKeepMeSignedInCheckbox               LocaleKey = "KeepMeSignedInCheckbox"
	LocaleKeyLinkedAccounts                       LocaleKey = "LinkedAccounts"
	LocaleKeyLoadingDotDot                        LocaleKey = "LoadingDotDot"
	LocaleKeyLogo                                 LocaleKey = "Logo"
	LocaleKeyNewPassword                          LocaleKey = "NewPassword"
	LocaleKeyNotFound                             LocaleKey = "NotFound"
	LocaleKeyOr                                   LocaleKey = "Or"
	LocaleKeyOrSignInWith                         LocaleKey = "OrSignInWith"
	LocaleKeyPasskeys                             LocaleKey = "Passkeys"
	LocaleKeyPassword                             LocaleKey = "Password"
	LocaleKeyPasswordConfirmIsRequired            LocaleKey = "PasswordConfirmIsRequired"
	LocaleKeyPasswordIsRequired                   LocaleKey = "PasswordIsRequired"
	LocaleKeyPasswordMinimum8Characters           LocaleKey = "PasswordMinimum8Characters"
	LocaleKeyPasswordRequired                     LocaleKey = "PasswordRequired"
	LocaleKeyPasswordTooWeak                      LocaleKey = "PasswordTooWeak"
	LocaleKeyPasswordsDoNotMatch                  LocaleKey = "PasswordsDoNotMatch"
	LocaleKeyProfile                              LocaleKey = "Profile"
	LocaleKeyProviderNotFound                     LocaleKey = "ProviderNotFound"
	LocaleKeyRageAccounts                         LocaleKey = "RageAccounts"
	LocaleKeyResetPassword                        LocaleKey = "ResetPassword"
	LocaleKeyResettingPasswordDotDot              LocaleKey = "ResettingPasswordDotDot"
	LocaleKeySignIn                               LocaleKey = "SignIn"
	LocaleKeySigninWithPasskey                    LocaleKey = "SigninWithPasskey"
	LocaleKeySigningInDotDot                      LocaleKey = "SigningInDotDot"
	LocaleKeySomethingWentWrong                   LocaleKey = "SomethingWentWrong"
	LocaleKeyStartOver                            LocaleKey = "StartOver"
	LocaleKeySubmit                               LocaleKey = "Submit"
	LocaleKeyUnexpectedErrorOccurred              LocaleKey = "UnexpectedErrorOccurred"
	LocaleKeyUserNotFoundF                        LocaleKey = "UserNotFoundF"
	LocaleKeyVerificationCode                     LocaleKey = "VerificationCode"
	LocaleKeyVerificationCodeRequired             LocaleKey = "VerificationCodeRequired"
	LocaleKeyVerifyCode                           LocaleKey = "VerifyCode"
	LocaleKeyVerifyingDotDot                      LocaleKey = "VerifyingDotDot"
	LocaleKeyWeEncounteredAnError                 LocaleKey = "WeEncounteredAnError"
	LocaleKeyWelcomeBack                          LocaleKey = "WelcomeBack"
)

// AllLocaleKeys makes it easy to list all values (great for tests, validation, etc.)
var AllLocaleKeys = []LocaleKey{
	LocaleKeyAccept,
	LocaleKeyAlreadyHaveAnAccount,
	LocaleKeyBack,
	LocaleKeyCheckingDotDot,
	LocaleKeyConfirmEmail,
	LocaleKeyConfirmEmailRequired,
	LocaleKeyConfirmPassword,
	LocaleKeyConfirmYourNewPassword,
	LocaleKeyContinue,
	LocaleKeyCookieConsentStatement,
	LocaleKeyCreateAccount,
	LocaleKeyCreateOne,
	LocaleKeyDidntReceiveCode,
	LocaleKeyDontHaveAnAccount,
	LocaleKeyEmailAddress,
	LocaleKeyEmailAlreadyInUse,
	LocaleKeyEmailIsRequired,
	LocaleKeyEmailNotFound,
	LocaleKeyEmailsDoNotMatch,
	LocaleKeyEnterEmailToContinue,
	LocaleKeyEnterTheVerificationCodeSentToF,
	LocaleKeyEnterValidEmail,
	LocaleKeyEnterYourEmail,
	LocaleKeyEnterYourEmailToContinue,
	LocaleKeyEnterYourNewPassword,
	LocaleKeyEnterYourNewPasswordBelow,
	LocaleKeyEnterYourPassword,
	LocaleKeyEnterYourPasswordF,
	LocaleKeyEnterYourVerficationCode,
	LocaleKeyError,
	LocaleKeyFailedToCreateAcctountF,
	LocaleKeyFailedToLookUpEmailF,
	LocaleKeyFillInYourDetailsToCreateANewAccount,
	LocaleKeyForgotPassword,
	LocaleKeyInvalidEmailAddress,
	LocaleKeyInvalidPassword,
	LocaleKeyInvalidRedirectURL,
	LocaleKeyInvalidResponseFromServer,
	LocaleKeyInvalidVerificationCode,
	LocaleKeyKeepMeSignedIn,
	LocaleKeyKeepMeSignedInDescription,
	LocaleKeyKeepMeSignedInCheckbox,
	LocaleKeyLinkedAccounts,
	LocaleKeyLoadingDotDot,
	LocaleKeyLogo,
	LocaleKeyNewPassword,
	LocaleKeyNotFound,
	LocaleKeyOr,
	LocaleKeyOrSignInWith,
	LocaleKeyPasskeys,
	LocaleKeyPassword,
	LocaleKeyPasswordConfirmIsRequired,
	LocaleKeyPasswordIsRequired,
	LocaleKeyPasswordMinimum8Characters,
	LocaleKeyPasswordRequired,
	LocaleKeyPasswordTooWeak,
	LocaleKeyPasswordsDoNotMatch,
	LocaleKeyProfile,
	LocaleKeyProviderNotFound,
	LocaleKeyRageAccounts,
	LocaleKeyResetPassword,
	LocaleKeyResettingPasswordDotDot,
	LocaleKeySignIn,
	LocaleKeySigninWithPasskey,
	LocaleKeySigningInDotDot,
	LocaleKeySomethingWentWrong,
	LocaleKeyStartOver,
	LocaleKeySubmit,
	LocaleKeyUnexpectedErrorOccurred,
	LocaleKeyUserNotFoundF,
	LocaleKeyVerificationCode,
	LocaleKeyVerificationCodeRequired,
	LocaleKeyVerifyCode,
	LocaleKeyVerifyingDotDot,
	LocaleKeyWeEncounteredAnError,
	LocaleKeyWelcomeBack,
}

// String satisfies fmt.Stringer (useful for logging, debugging)
func (l LocaleKey) String() string {
	return string(l)
}

// ParseLocaleKey parses a string into a LocaleKey with validation
func ParseLocaleKey(s string) (LocaleKey, error) {
	for _, l := range AllLocaleKeys {
		if l.String() == s {
			return l, nil
		}
	}
	return "", fmt.Errorf("invalid LocaleKey value: %q", s)
}
