// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/oidc/models/idp.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OIDCProtocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OIDCProtocol) Reset() {
	*x = OIDCProtocol{}
	mi := &file_proto_oidc_models_idp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCProtocol) ProtoMessage() {}

func (x *OIDCProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_idp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCProtocol.ProtoReflect.Descriptor instead.
func (*OIDCProtocol) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_idp_proto_rawDescGZIP(), []int{0}
}

func (x *OIDCProtocol) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *OIDCProtocol) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OIDCProtocol) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OIDCProtocol) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type GithubOAuth2Protocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubOAuth2Protocol) Reset() {
	*x = GithubOAuth2Protocol{}
	mi := &file_proto_oidc_models_idp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubOAuth2Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubOAuth2Protocol) ProtoMessage() {}

func (x *GithubOAuth2Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_idp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubOAuth2Protocol.ProtoReflect.Descriptor instead.
func (*GithubOAuth2Protocol) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_idp_proto_rawDescGZIP(), []int{1}
}

func (x *GithubOAuth2Protocol) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GithubOAuth2Protocol) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type OAuth2Protocol struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientId              string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret          string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Scope                 string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	AuthorizationEndpoint string                 `protobuf:"bytes,4,opt,name=authorization_endpoint,json=authorizationEndpoint,proto3" json:"authorization_endpoint,omitempty"`
	TokenEndpoint         string                 `protobuf:"bytes,5,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OAuth2Protocol) Reset() {
	*x = OAuth2Protocol{}
	mi := &file_proto_oidc_models_idp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Protocol) ProtoMessage() {}

func (x *OAuth2Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_idp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Protocol.ProtoReflect.Descriptor instead.
func (*OAuth2Protocol) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_idp_proto_rawDescGZIP(), []int{2}
}

func (x *OAuth2Protocol) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuth2Protocol) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OAuth2Protocol) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OAuth2Protocol) GetAuthorizationEndpoint() string {
	if x != nil {
		return x.AuthorizationEndpoint
	}
	return ""
}

func (x *OAuth2Protocol) GetTokenEndpoint() string {
	if x != nil {
		return x.TokenEndpoint
	}
	return ""
}

type Protocol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Protocol_Oidc
	//	*Protocol_Oauth2
	//	*Protocol_Github
	Value         isProtocol_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	mi := &file_proto_oidc_models_idp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_idp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_idp_proto_rawDescGZIP(), []int{3}
}

func (x *Protocol) GetValue() isProtocol_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Protocol) GetOidc() *OIDCProtocol {
	if x != nil {
		if x, ok := x.Value.(*Protocol_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

func (x *Protocol) GetOauth2() *OAuth2Protocol {
	if x != nil {
		if x, ok := x.Value.(*Protocol_Oauth2); ok {
			return x.Oauth2
		}
	}
	return nil
}

func (x *Protocol) GetGithub() *GithubOAuth2Protocol {
	if x != nil {
		if x, ok := x.Value.(*Protocol_Github); ok {
			return x.Github
		}
	}
	return nil
}

type isProtocol_Value interface {
	isProtocol_Value()
}

type Protocol_Oidc struct {
	Oidc *OIDCProtocol `protobuf:"bytes,1,opt,name=oidc,proto3,oneof"`
}

type Protocol_Oauth2 struct {
	Oauth2 *OAuth2Protocol `protobuf:"bytes,2,opt,name=oauth2,proto3,oneof"`
}

type Protocol_Github struct {
	Github *GithubOAuth2Protocol `protobuf:"bytes,3,opt,name=github,proto3,oneof"`
}

func (*Protocol_Oidc) isProtocol_Value() {}

func (*Protocol_Oauth2) isProtocol_Value() {}

func (*Protocol_Github) isProtocol_Value() {}

type IDP struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled                   bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Slug                      string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                      string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description               string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Protocol                  *Protocol              `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Metadata                  map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClaimedDomains            []string               `protobuf:"bytes,8,rep,name=claimed_domains,json=claimedDomains,proto3" json:"claimed_domains,omitempty"`
	Hidden                    bool                   `protobuf:"varint,9,opt,name=hidden,proto3" json:"hidden,omitempty"`
	EmailVerificationRequired bool                   `protobuf:"varint,10,opt,name=email_verification_required,json=emailVerificationRequired,proto3" json:"email_verification_required,omitempty"`
	AutoCreate                bool                   `protobuf:"varint,11,opt,name=auto_create,json=autoCreate,proto3" json:"auto_create,omitempty"`
	MultiFactorRequired       bool                   `protobuf:"varint,12,opt,name=multi_factor_required,json=multiFactorRequired,proto3" json:"multi_factor_required,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *IDP) Reset() {
	*x = IDP{}
	mi := &file_proto_oidc_models_idp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDP) ProtoMessage() {}

func (x *IDP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_idp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDP.ProtoReflect.Descriptor instead.
func (*IDP) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_idp_proto_rawDescGZIP(), []int{4}
}

func (x *IDP) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IDP) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *IDP) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *IDP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IDP) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IDP) GetProtocol() *Protocol {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *IDP) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IDP) GetClaimedDomains() []string {
	if x != nil {
		return x.ClaimedDomains
	}
	return nil
}

func (x *IDP) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *IDP) GetEmailVerificationRequired() bool {
	if x != nil {
		return x.EmailVerificationRequired
	}
	return false
}

func (x *IDP) GetAutoCreate() bool {
	if x != nil {
		return x.AutoCreate
	}
	return false
}

func (x *IDP) GetMultiFactorRequired() bool {
	if x != nil {
		return x.MultiFactorRequired
	}
	return false
}

type IDPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idps          []*IDP                 `protobuf:"bytes,1,rep,name=idps,proto3" json:"idps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDPs) Reset() {
	*x = IDPs{}
	mi := &file_proto_oidc_models_idp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDPs) ProtoMessage() {}

func (x *IDPs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_idp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDPs.ProtoReflect.Descriptor instead.
func (*IDPs) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_idp_proto_rawDescGZIP(), []int{5}
}

func (x *IDPs) GetIdps() []*IDP {
	if x != nil {
		return x.Idps
	}
	return nil
}

var File_proto_oidc_models_idp_proto protoreflect.FileDescriptor

const file_proto_oidc_models_idp_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/oidc/models/idp.proto\x12\x11proto.oidc.models\x1a google/protobuf/descriptor.proto\"\x84\x01\n" +
	"\fOIDCProtocol\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"X\n" +
	"\x14GithubOAuth2Protocol\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\"\xc6\x01\n" +
	"\x0eOAuth2Protocol\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x125\n" +
	"\x16authorization_endpoint\x18\x04 \x01(\tR\x15authorizationEndpoint\x12%\n" +
	"\x0etoken_endpoint\x18\x05 \x01(\tR\rtokenEndpoint\"\xca\x01\n" +
	"\bProtocol\x125\n" +
	"\x04oidc\x18\x01 \x01(\v2\x1f.proto.oidc.models.OIDCProtocolH\x00R\x04oidc\x12;\n" +
	"\x06oauth2\x18\x02 \x01(\v2!.proto.oidc.models.OAuth2ProtocolH\x00R\x06oauth2\x12A\n" +
	"\x06github\x18\x03 \x01(\v2'.proto.oidc.models.GithubOAuth2ProtocolH\x00R\x06githubB\a\n" +
	"\x05value\"\x87\x04\n" +
	"\x03IDP\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x127\n" +
	"\bprotocol\x18\x06 \x01(\v2\x1b.proto.oidc.models.ProtocolR\bprotocol\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.proto.oidc.models.IDP.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fclaimed_domains\x18\b \x03(\tR\x0eclaimedDomains\x12\x16\n" +
	"\x06hidden\x18\t \x01(\bR\x06hidden\x12>\n" +
	"\x1bemail_verification_required\x18\n" +
	" \x01(\bR\x19emailVerificationRequired\x12\x1f\n" +
	"\vauto_create\x18\v \x01(\bR\n" +
	"autoCreate\x122\n" +
	"\x15multi_factor_required\x18\f \x01(\bR\x13multiFactorRequired\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x04IDPs\x12*\n" +
	"\x04idps\x18\x01 \x03(\v2\x16.proto.oidc.models.IDPR\x04idpsB\x91\x01\n" +
	"\x1fcom.fluffybunny.rageoidc.modelsP\x01ZIgithub.com/fluffy-bunny/fluffycore-rage-identity/proto/oidc/models;models\xaa\x02 FluffyBunny.RageOidc.Oidc.Modelsb\x06proto3"

var (
	file_proto_oidc_models_idp_proto_rawDescOnce sync.Once
	file_proto_oidc_models_idp_proto_rawDescData []byte
)

func file_proto_oidc_models_idp_proto_rawDescGZIP() []byte {
	file_proto_oidc_models_idp_proto_rawDescOnce.Do(func() {
		file_proto_oidc_models_idp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oidc_models_idp_proto_rawDesc), len(file_proto_oidc_models_idp_proto_rawDesc)))
	})
	return file_proto_oidc_models_idp_proto_rawDescData
}

var file_proto_oidc_models_idp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_oidc_models_idp_proto_goTypes = []any{
	(*OIDCProtocol)(nil),         // 0: proto.oidc.models.OIDCProtocol
	(*GithubOAuth2Protocol)(nil), // 1: proto.oidc.models.GithubOAuth2Protocol
	(*OAuth2Protocol)(nil),       // 2: proto.oidc.models.OAuth2Protocol
	(*Protocol)(nil),             // 3: proto.oidc.models.Protocol
	(*IDP)(nil),                  // 4: proto.oidc.models.IDP
	(*IDPs)(nil),                 // 5: proto.oidc.models.IDPs
	nil,                          // 6: proto.oidc.models.IDP.MetadataEntry
}
var file_proto_oidc_models_idp_proto_depIdxs = []int32{
	0, // 0: proto.oidc.models.Protocol.oidc:type_name -> proto.oidc.models.OIDCProtocol
	2, // 1: proto.oidc.models.Protocol.oauth2:type_name -> proto.oidc.models.OAuth2Protocol
	1, // 2: proto.oidc.models.Protocol.github:type_name -> proto.oidc.models.GithubOAuth2Protocol
	3, // 3: proto.oidc.models.IDP.protocol:type_name -> proto.oidc.models.Protocol
	6, // 4: proto.oidc.models.IDP.metadata:type_name -> proto.oidc.models.IDP.MetadataEntry
	4, // 5: proto.oidc.models.IDPs.idps:type_name -> proto.oidc.models.IDP
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_oidc_models_idp_proto_init() }
func file_proto_oidc_models_idp_proto_init() {
	if File_proto_oidc_models_idp_proto != nil {
		return
	}
	file_proto_oidc_models_idp_proto_msgTypes[3].OneofWrappers = []any{
		(*Protocol_Oidc)(nil),
		(*Protocol_Oauth2)(nil),
		(*Protocol_Github)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oidc_models_idp_proto_rawDesc), len(file_proto_oidc_models_idp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_oidc_models_idp_proto_goTypes,
		DependencyIndexes: file_proto_oidc_models_idp_proto_depIdxs,
		MessageInfos:      file_proto_oidc_models_idp_proto_msgTypes,
	}.Build()
	File_proto_oidc_models_idp_proto = out.File
	file_proto_oidc_models_idp_proto_goTypes = nil
	file_proto_oidc_models_idp_proto_depIdxs = nil
}
