// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: proto/oidc/models/user.proto

package models

import (
	types "github.com/fluffy-bunny/fluffycore-rage-oidc/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserState int32

const (
	UserState_USER_STATE_UNSPECIFIED UserState = 0
	UserState_USER_STATE_ACTIVE      UserState = 1
	UserState_USER_STATE_DISABLED    UserState = 2
	UserState_USER_STATE_DELETED     UserState = 3
	UserState_USER_STATE_PENDING     UserState = 4
)

// Enum value maps for UserState.
var (
	UserState_name = map[int32]string{
		0: "USER_STATE_UNSPECIFIED",
		1: "USER_STATE_ACTIVE",
		2: "USER_STATE_DISABLED",
		3: "USER_STATE_DELETED",
		4: "USER_STATE_PENDING",
	}
	UserState_value = map[string]int32{
		"USER_STATE_UNSPECIFIED": 0,
		"USER_STATE_ACTIVE":      1,
		"USER_STATE_DISABLED":    2,
		"USER_STATE_DELETED":     3,
		"USER_STATE_PENDING":     4,
	}
)

func (x UserState) Enum() *UserState {
	p := new(UserState)
	*p = x
	return p
}

func (x UserState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_oidc_models_user_proto_enumTypes[0].Descriptor()
}

func (UserState) Type() protoreflect.EnumType {
	return &file_proto_oidc_models_user_proto_enumTypes[0]
}

func (x UserState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserState.Descriptor instead.
func (UserState) EnumDescriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{0}
}

type UserStateFilterExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eq UserState   `protobuf:"varint,1,opt,name=eq,proto3,enum=proto.oidc.models.UserState" json:"eq,omitempty"`
	In []UserState `protobuf:"varint,2,rep,packed,name=in,proto3,enum=proto.oidc.models.UserState" json:"in,omitempty"`
}

func (x *UserStateFilterExpression) Reset() {
	*x = UserStateFilterExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStateFilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStateFilterExpression) ProtoMessage() {}

func (x *UserStateFilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStateFilterExpression.ProtoReflect.Descriptor instead.
func (*UserStateFilterExpression) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserStateFilterExpression) GetEq() UserState {
	if x != nil {
		return x.Eq
	}
	return UserState_USER_STATE_UNSPECIFIED
}

func (x *UserStateFilterExpression) GetIn() []UserState {
	if x != nil {
		return x.In
	}
	return nil
}

type UserStateValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vale UserState `protobuf:"varint,1,opt,name=vale,proto3,enum=proto.oidc.models.UserState" json:"vale,omitempty"`
}

func (x *UserStateValue) Reset() {
	*x = UserStateValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStateValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStateValue) ProtoMessage() {}

func (x *UserStateValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStateValue.ProtoReflect.Descriptor instead.
func (*UserStateValue) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserStateValue) GetVale() UserState {
	if x != nil {
		return x.Vale
	}
	return UserState_USER_STATE_UNSPECIFIED
}

type Password struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Password) Reset() {
	*x = Password{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{2}
}

func (x *Password) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type PasswordUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *PasswordUpdate) Reset() {
	*x = PasswordUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordUpdate) ProtoMessage() {}

func (x *PasswordUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordUpdate.ProtoReflect.Descriptor instead.
func (*PasswordUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{3}
}

func (x *PasswordUpdate) GetHash() *wrapperspb.StringValue {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject       string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	IdpSlug       string `protobuf:"bytes,2,opt,name=idp_slug,json=idpSlug,proto3" json:"idp_slug,omitempty"`
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{4}
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetIdpSlug() string {
	if x != nil {
		return x.IdpSlug
	}
	return ""
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Identity) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

type LinkedIdentities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identities []*Identity `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
}

func (x *LinkedIdentities) Reset() {
	*x = LinkedIdentities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkedIdentities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedIdentities) ProtoMessage() {}

func (x *LinkedIdentities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedIdentities.ProtoReflect.Descriptor instead.
func (*LinkedIdentities) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{5}
}

func (x *LinkedIdentities) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type IdentityUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject string                  `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *IdentityUpdate) Reset() {
	*x = IdentityUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityUpdate) ProtoMessage() {}

func (x *IdentityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityUpdate.ProtoReflect.Descriptor instead.
func (*IdentityUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityUpdate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IdentityUpdate) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

type LinkedIdentitiesUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//
	//	*LinkedIdentitiesUpdate_Granular_
	//	*LinkedIdentitiesUpdate_Replace
	Update isLinkedIdentitiesUpdate_Update `protobuf_oneof:"update"`
}

func (x *LinkedIdentitiesUpdate) Reset() {
	*x = LinkedIdentitiesUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkedIdentitiesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedIdentitiesUpdate) ProtoMessage() {}

func (x *LinkedIdentitiesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedIdentitiesUpdate.ProtoReflect.Descriptor instead.
func (*LinkedIdentitiesUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{7}
}

func (m *LinkedIdentitiesUpdate) GetUpdate() isLinkedIdentitiesUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *LinkedIdentitiesUpdate) GetGranular() *LinkedIdentitiesUpdate_Granular {
	if x, ok := x.GetUpdate().(*LinkedIdentitiesUpdate_Granular_); ok {
		return x.Granular
	}
	return nil
}

func (x *LinkedIdentitiesUpdate) GetReplace() *LinkedIdentities {
	if x, ok := x.GetUpdate().(*LinkedIdentitiesUpdate_Replace); ok {
		return x.Replace
	}
	return nil
}

type isLinkedIdentitiesUpdate_Update interface {
	isLinkedIdentitiesUpdate_Update()
}

type LinkedIdentitiesUpdate_Granular_ struct {
	Granular *LinkedIdentitiesUpdate_Granular `protobuf:"bytes,1,opt,name=granular,proto3,oneof"`
}

type LinkedIdentitiesUpdate_Replace struct {
	Replace *LinkedIdentities `protobuf:"bytes,2,opt,name=replace,proto3,oneof"`
}

func (*LinkedIdentitiesUpdate_Granular_) isLinkedIdentitiesUpdate_Update() {}

func (*LinkedIdentitiesUpdate_Replace) isLinkedIdentitiesUpdate_Update() {}

type Recovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails *types.StringValues `protobuf:"bytes,1,opt,name=emails,proto3" json:"emails,omitempty"`
}

func (x *Recovery) Reset() {
	*x = Recovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recovery) ProtoMessage() {}

func (x *Recovery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recovery.ProtoReflect.Descriptor instead.
func (*Recovery) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{8}
}

func (x *Recovery) GetEmails() *types.StringValues {
	if x != nil {
		return x.Emails
	}
	return nil
}

type RecoveryUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails *types.StringArrayUpdate `protobuf:"bytes,1,opt,name=emails,proto3" json:"emails,omitempty"`
}

func (x *RecoveryUpdate) Reset() {
	*x = RecoveryUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoveryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryUpdate) ProtoMessage() {}

func (x *RecoveryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryUpdate.ProtoReflect.Descriptor instead.
func (*RecoveryUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{9}
}

func (x *RecoveryUpdate) GetEmails() *types.StringArrayUpdate {
	if x != nil {
		return x.Emails
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootIdentity     *Identity         `protobuf:"bytes,1,opt,name=root_identity,json=rootIdentity,proto3" json:"root_identity,omitempty"`
	LinkedIdentities *LinkedIdentities `protobuf:"bytes,2,opt,name=linked_identities,json=linkedIdentities,proto3" json:"linked_identities,omitempty"`
	Recovery         *Recovery         `protobuf:"bytes,3,opt,name=recovery,proto3" json:"recovery,omitempty"`
	Password         *Password         `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	State            UserState         `protobuf:"varint,5,opt,name=state,proto3,enum=proto.oidc.models.UserState" json:"state,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{10}
}

func (x *User) GetRootIdentity() *Identity {
	if x != nil {
		return x.RootIdentity
	}
	return nil
}

func (x *User) GetLinkedIdentities() *LinkedIdentities {
	if x != nil {
		return x.LinkedIdentities
	}
	return nil
}

func (x *User) GetRecovery() *Recovery {
	if x != nil {
		return x.Recovery
	}
	return nil
}

func (x *User) GetPassword() *Password {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *User) GetState() UserState {
	if x != nil {
		return x.State
	}
	return UserState_USER_STATE_UNSPECIFIED
}

type UserUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootIdentity     *IdentityUpdate         `protobuf:"bytes,1,opt,name=root_identity,json=rootIdentity,proto3" json:"root_identity,omitempty"`
	LinkedIdentities *LinkedIdentitiesUpdate `protobuf:"bytes,2,opt,name=linked_identities,json=linkedIdentities,proto3" json:"linked_identities,omitempty"`
	Recovery         *RecoveryUpdate         `protobuf:"bytes,3,opt,name=recovery,proto3" json:"recovery,omitempty"`
	Password         *PasswordUpdate         `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	State            *UserStateValue         `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *UserUpdate) Reset() {
	*x = UserUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdate) ProtoMessage() {}

func (x *UserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdate.ProtoReflect.Descriptor instead.
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserUpdate) GetRootIdentity() *IdentityUpdate {
	if x != nil {
		return x.RootIdentity
	}
	return nil
}

func (x *UserUpdate) GetLinkedIdentities() *LinkedIdentitiesUpdate {
	if x != nil {
		return x.LinkedIdentities
	}
	return nil
}

func (x *UserUpdate) GetRecovery() *RecoveryUpdate {
	if x != nil {
		return x.Recovery
	}
	return nil
}

func (x *UserUpdate) GetPassword() *PasswordUpdate {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *UserUpdate) GetState() *UserStateValue {
	if x != nil {
		return x.State
	}
	return nil
}

type LinkedIdentitiesUpdate_Granular struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add    []*Identity `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove []*Identity `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
}

func (x *LinkedIdentitiesUpdate_Granular) Reset() {
	*x = LinkedIdentitiesUpdate_Granular{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_oidc_models_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkedIdentitiesUpdate_Granular) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedIdentitiesUpdate_Granular) ProtoMessage() {}

func (x *LinkedIdentitiesUpdate_Granular) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedIdentitiesUpdate_Granular.ProtoReflect.Descriptor instead.
func (*LinkedIdentitiesUpdate_Granular) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{7, 0}
}

func (x *LinkedIdentitiesUpdate_Granular) GetAdd() []*Identity {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *LinkedIdentitiesUpdate_Granular) GetRemove() []*Identity {
	if x != nil {
		return x.Remove
	}
	return nil
}

var File_proto_oidc_models_user_proto protoreflect.FileDescriptor

var file_proto_oidc_models_user_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x69, 0x64, 0x63, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x19,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x02, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69,
	0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x42, 0x04, 0xc8, 0xcf, 0x24, 0x0a, 0x52, 0x02, 0x65, 0x71, 0x12, 0x32, 0x0a,
	0x02, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x04, 0xc8, 0xcf, 0x24, 0x21, 0x52, 0x02, 0x69,
	0x6e, 0x3a, 0x04, 0xe0, 0xd5, 0x24, 0x01, 0x22, 0x42, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x76, 0x61, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x65, 0x22, 0x1e, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x42, 0x0a, 0x0e, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x7c, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x70, 0x5f, 0x73, 0x6c, 0x75,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x70, 0x53, 0x6c, 0x75, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x4f, 0x0a,
	0x10, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x3b, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69,
	0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x5e,
	0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xa5,
	0x02, 0x0a, 0x16, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x50, 0x0a, 0x08, 0x67, 0x72, 0x61,
	0x6e, 0x75, 0x6c, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x48,
	0x00, 0x52, 0x08, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x3f, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x1a, 0x6e, 0x0a, 0x08,
	0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x2d, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69,
	0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x3d, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x06, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x48, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22,
	0xc0, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0d, 0x72, 0x6f, 0x6f, 0x74,
	0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x72, 0x6f,
	0x6f, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x11, 0x6c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69,
	0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x10, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08,
	0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x32,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0xe3, 0x02, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x46, 0x0a, 0x0d, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x72, 0x6f, 0x6f,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x56, 0x0a, 0x11, 0x6c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64,
	0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x10, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x3d, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x12, 0x3d, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x37, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x69, 0x64, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x87, 0x01, 0x0a, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x04, 0x42, 0x8d, 0x01, 0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x75, 0x66, 0x66,
	0x79, 0x62, 0x75, 0x6e, 0x6e, 0x79, 0x2e, 0x72, 0x61, 0x67, 0x65, 0x6f, 0x69, 0x64, 0x63, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x50, 0x01, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x75, 0x66, 0x66, 0x79, 0x2d, 0x62, 0x75, 0x6e, 0x6e,
	0x79, 0x2f, 0x66, 0x6c, 0x75, 0x66, 0x66, 0x79, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x72, 0x61, 0x67,
	0x65, 0x2d, 0x6f, 0x69, 0x64, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x69, 0x64,
	0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0xaa,
	0x02, 0x20, 0x46, 0x6c, 0x75, 0x66, 0x66, 0x79, 0x42, 0x75, 0x6e, 0x6e, 0x79, 0x2e, 0x52, 0x61,
	0x67, 0x65, 0x4f, 0x69, 0x64, 0x63, 0x2e, 0x4f, 0x69, 0x64, 0x63, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_oidc_models_user_proto_rawDescOnce sync.Once
	file_proto_oidc_models_user_proto_rawDescData = file_proto_oidc_models_user_proto_rawDesc
)

func file_proto_oidc_models_user_proto_rawDescGZIP() []byte {
	file_proto_oidc_models_user_proto_rawDescOnce.Do(func() {
		file_proto_oidc_models_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_oidc_models_user_proto_rawDescData)
	})
	return file_proto_oidc_models_user_proto_rawDescData
}

var file_proto_oidc_models_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_oidc_models_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_oidc_models_user_proto_goTypes = []interface{}{
	(UserState)(0),                          // 0: proto.oidc.models.UserState
	(*UserStateFilterExpression)(nil),       // 1: proto.oidc.models.UserStateFilterExpression
	(*UserStateValue)(nil),                  // 2: proto.oidc.models.UserStateValue
	(*Password)(nil),                        // 3: proto.oidc.models.Password
	(*PasswordUpdate)(nil),                  // 4: proto.oidc.models.PasswordUpdate
	(*Identity)(nil),                        // 5: proto.oidc.models.Identity
	(*LinkedIdentities)(nil),                // 6: proto.oidc.models.LinkedIdentities
	(*IdentityUpdate)(nil),                  // 7: proto.oidc.models.IdentityUpdate
	(*LinkedIdentitiesUpdate)(nil),          // 8: proto.oidc.models.LinkedIdentitiesUpdate
	(*Recovery)(nil),                        // 9: proto.oidc.models.Recovery
	(*RecoveryUpdate)(nil),                  // 10: proto.oidc.models.RecoveryUpdate
	(*User)(nil),                            // 11: proto.oidc.models.User
	(*UserUpdate)(nil),                      // 12: proto.oidc.models.UserUpdate
	(*LinkedIdentitiesUpdate_Granular)(nil), // 13: proto.oidc.models.LinkedIdentitiesUpdate.Granular
	(*wrapperspb.StringValue)(nil),          // 14: google.protobuf.StringValue
	(*types.StringValues)(nil),              // 15: proto.types.StringValues
	(*types.StringArrayUpdate)(nil),         // 16: proto.types.StringArrayUpdate
}
var file_proto_oidc_models_user_proto_depIdxs = []int32{
	0,  // 0: proto.oidc.models.UserStateFilterExpression.eq:type_name -> proto.oidc.models.UserState
	0,  // 1: proto.oidc.models.UserStateFilterExpression.in:type_name -> proto.oidc.models.UserState
	0,  // 2: proto.oidc.models.UserStateValue.vale:type_name -> proto.oidc.models.UserState
	14, // 3: proto.oidc.models.PasswordUpdate.hash:type_name -> google.protobuf.StringValue
	5,  // 4: proto.oidc.models.LinkedIdentities.identities:type_name -> proto.oidc.models.Identity
	14, // 5: proto.oidc.models.IdentityUpdate.email:type_name -> google.protobuf.StringValue
	13, // 6: proto.oidc.models.LinkedIdentitiesUpdate.granular:type_name -> proto.oidc.models.LinkedIdentitiesUpdate.Granular
	6,  // 7: proto.oidc.models.LinkedIdentitiesUpdate.replace:type_name -> proto.oidc.models.LinkedIdentities
	15, // 8: proto.oidc.models.Recovery.emails:type_name -> proto.types.StringValues
	16, // 9: proto.oidc.models.RecoveryUpdate.emails:type_name -> proto.types.StringArrayUpdate
	5,  // 10: proto.oidc.models.User.root_identity:type_name -> proto.oidc.models.Identity
	6,  // 11: proto.oidc.models.User.linked_identities:type_name -> proto.oidc.models.LinkedIdentities
	9,  // 12: proto.oidc.models.User.recovery:type_name -> proto.oidc.models.Recovery
	3,  // 13: proto.oidc.models.User.password:type_name -> proto.oidc.models.Password
	0,  // 14: proto.oidc.models.User.state:type_name -> proto.oidc.models.UserState
	7,  // 15: proto.oidc.models.UserUpdate.root_identity:type_name -> proto.oidc.models.IdentityUpdate
	8,  // 16: proto.oidc.models.UserUpdate.linked_identities:type_name -> proto.oidc.models.LinkedIdentitiesUpdate
	10, // 17: proto.oidc.models.UserUpdate.recovery:type_name -> proto.oidc.models.RecoveryUpdate
	4,  // 18: proto.oidc.models.UserUpdate.password:type_name -> proto.oidc.models.PasswordUpdate
	2,  // 19: proto.oidc.models.UserUpdate.state:type_name -> proto.oidc.models.UserStateValue
	5,  // 20: proto.oidc.models.LinkedIdentitiesUpdate.Granular.add:type_name -> proto.oidc.models.Identity
	5,  // 21: proto.oidc.models.LinkedIdentitiesUpdate.Granular.remove:type_name -> proto.oidc.models.Identity
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_oidc_models_user_proto_init() }
func file_proto_oidc_models_user_proto_init() {
	if File_proto_oidc_models_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_oidc_models_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStateFilterExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStateValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Password); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkedIdentities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkedIdentitiesUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoveryUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_oidc_models_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkedIdentitiesUpdate_Granular); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_oidc_models_user_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*LinkedIdentitiesUpdate_Granular_)(nil),
		(*LinkedIdentitiesUpdate_Replace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_oidc_models_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_oidc_models_user_proto_goTypes,
		DependencyIndexes: file_proto_oidc_models_user_proto_depIdxs,
		EnumInfos:         file_proto_oidc_models_user_proto_enumTypes,
		MessageInfos:      file_proto_oidc_models_user_proto_msgTypes,
	}.Build()
	File_proto_oidc_models_user_proto = out.File
	file_proto_oidc_models_user_proto_rawDesc = nil
	file_proto_oidc_models_user_proto_goTypes = nil
	file_proto_oidc_models_user_proto_depIdxs = nil
}
