// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/oidc/models/user.proto

package models

import (
	types "github.com/fluffy-bunny/fluffycore-rage-identity/proto/types"
	webauthn "github.com/fluffy-bunny/fluffycore-rage-identity/proto/types/webauthn"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RageUserState int32

const (
	RageUserState_USER_STATE_UNSPECIFIED RageUserState = 0
	RageUserState_USER_STATE_ACTIVE      RageUserState = 1
	RageUserState_USER_STATE_DISABLED    RageUserState = 2
	RageUserState_USER_STATE_DELETED     RageUserState = 3
	RageUserState_USER_STATE_PENDING     RageUserState = 4
)

// Enum value maps for RageUserState.
var (
	RageUserState_name = map[int32]string{
		0: "USER_STATE_UNSPECIFIED",
		1: "USER_STATE_ACTIVE",
		2: "USER_STATE_DISABLED",
		3: "USER_STATE_DELETED",
		4: "USER_STATE_PENDING",
	}
	RageUserState_value = map[string]int32{
		"USER_STATE_UNSPECIFIED": 0,
		"USER_STATE_ACTIVE":      1,
		"USER_STATE_DISABLED":    2,
		"USER_STATE_DELETED":     3,
		"USER_STATE_PENDING":     4,
	}
)

func (x RageUserState) Enum() *RageUserState {
	p := new(RageUserState)
	*p = x
	return p
}

func (x RageUserState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RageUserState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_oidc_models_user_proto_enumTypes[0].Descriptor()
}

func (RageUserState) Type() protoreflect.EnumType {
	return &file_proto_oidc_models_user_proto_enumTypes[0]
}

func (x RageUserState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RageUserState.Descriptor instead.
func (RageUserState) EnumDescriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{0}
}

type RageUserStateValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         RageUserState          `protobuf:"varint,1,opt,name=value,proto3,enum=proto.oidc.models.RageUserState" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RageUserStateValue) Reset() {
	*x = RageUserStateValue{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RageUserStateValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RageUserStateValue) ProtoMessage() {}

func (x *RageUserStateValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RageUserStateValue.ProtoReflect.Descriptor instead.
func (*RageUserStateValue) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{0}
}

func (x *RageUserStateValue) GetValue() RageUserState {
	if x != nil {
		return x.Value
	}
	return RageUserState_USER_STATE_UNSPECIFIED
}

type Password struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Password) Reset() {
	*x = Password{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{1}
}

func (x *Password) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type PasswordUpdate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Hash          *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordUpdate) Reset() {
	*x = PasswordUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordUpdate) ProtoMessage() {}

func (x *PasswordUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordUpdate.ProtoReflect.Descriptor instead.
func (*PasswordUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{2}
}

func (x *PasswordUpdate) GetHash() *wrapperspb.StringValue {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	IdpSlug       string                 `protobuf:"bytes,2,opt,name=idp_slug,json=idpSlug,proto3" json:"idp_slug,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	CreatedOn     *timestamppb.Timestamp `protobuf:"bytes,50,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn     *timestamppb.Timestamp `protobuf:"bytes,51,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{3}
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetIdpSlug() string {
	if x != nil {
		return x.IdpSlug
	}
	return ""
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Identity) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *Identity) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *Identity) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

type IdentityFilter struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Subject       *types.IDFilterExpression     `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	IdpSlug       *types.IDFilterExpression     `protobuf:"bytes,2,opt,name=idp_slug,json=idpSlug,proto3" json:"idp_slug,omitempty"`
	Email         *types.StringFilterExpression `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityFilter) Reset() {
	*x = IdentityFilter{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityFilter) ProtoMessage() {}

func (x *IdentityFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityFilter.ProtoReflect.Descriptor instead.
func (*IdentityFilter) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityFilter) GetSubject() *types.IDFilterExpression {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *IdentityFilter) GetIdpSlug() *types.IDFilterExpression {
	if x != nil {
		return x.IdpSlug
	}
	return nil
}

func (x *IdentityFilter) GetEmail() *types.StringFilterExpression {
	if x != nil {
		return x.Email
	}
	return nil
}

type OIDCIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	IdpSlug       string                 `protobuf:"bytes,2,opt,name=idp_slug,json=idpSlug,proto3" json:"idp_slug,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Acr           []string               `protobuf:"bytes,5,rep,name=acr,proto3" json:"acr,omitempty"`
	Amr           []string               `protobuf:"bytes,6,rep,name=amr,proto3" json:"amr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OIDCIdentity) Reset() {
	*x = OIDCIdentity{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCIdentity) ProtoMessage() {}

func (x *OIDCIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCIdentity.ProtoReflect.Descriptor instead.
func (*OIDCIdentity) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{5}
}

func (x *OIDCIdentity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OIDCIdentity) GetIdpSlug() string {
	if x != nil {
		return x.IdpSlug
	}
	return ""
}

func (x *OIDCIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OIDCIdentity) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *OIDCIdentity) GetAcr() []string {
	if x != nil {
		return x.Acr
	}
	return nil
}

func (x *OIDCIdentity) GetAmr() []string {
	if x != nil {
		return x.Amr
	}
	return nil
}

type ExternalOauth2Request struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdpHint               string                 `protobuf:"bytes,1,opt,name=idp_hint,json=idpHint,proto3" json:"idp_hint,omitempty"`
	ClientId              string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CodeChallenge         string                 `protobuf:"bytes,3,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	CodeChallengeMethod   string                 `protobuf:"bytes,4,opt,name=code_challenge_method,json=codeChallengeMethod,proto3" json:"code_challenge_method,omitempty"`
	State                 string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CodeChallengeVerifier string                 `protobuf:"bytes,6,opt,name=code_challenge_verifier,json=codeChallengeVerifier,proto3" json:"code_challenge_verifier,omitempty"`
	Nonce                 string                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Directive             string                 `protobuf:"bytes,8,opt,name=directive,proto3" json:"directive,omitempty"`
	ParentState           string                 `protobuf:"bytes,9,opt,name=parent_state,json=parentState,proto3" json:"parent_state,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExternalOauth2Request) Reset() {
	*x = ExternalOauth2Request{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalOauth2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalOauth2Request) ProtoMessage() {}

func (x *ExternalOauth2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalOauth2Request.ProtoReflect.Descriptor instead.
func (*ExternalOauth2Request) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{6}
}

func (x *ExternalOauth2Request) GetIdpHint() string {
	if x != nil {
		return x.IdpHint
	}
	return ""
}

func (x *ExternalOauth2Request) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ExternalOauth2Request) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

func (x *ExternalOauth2Request) GetCodeChallengeMethod() string {
	if x != nil {
		return x.CodeChallengeMethod
	}
	return ""
}

func (x *ExternalOauth2Request) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExternalOauth2Request) GetCodeChallengeVerifier() string {
	if x != nil {
		return x.CodeChallengeVerifier
	}
	return ""
}

func (x *ExternalOauth2Request) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ExternalOauth2Request) GetDirective() string {
	if x != nil {
		return x.Directive
	}
	return ""
}

func (x *ExternalOauth2Request) GetParentState() string {
	if x != nil {
		return x.ParentState
	}
	return ""
}

type ExternalOauth2State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ExternalOauth2Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Identity      *Identity              `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalOauth2State) Reset() {
	*x = ExternalOauth2State{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalOauth2State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalOauth2State) ProtoMessage() {}

func (x *ExternalOauth2State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalOauth2State.ProtoReflect.Descriptor instead.
func (*ExternalOauth2State) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{7}
}

func (x *ExternalOauth2State) GetRequest() *ExternalOauth2Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExternalOauth2State) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type AuthorizationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClientId            string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResponseType        string                 `protobuf:"bytes,2,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	Scope               string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	State               string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUri         string                 `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Audience            string                 `protobuf:"bytes,6,opt,name=audience,proto3" json:"audience,omitempty"`
	CodeChallenge       string                 `protobuf:"bytes,7,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	CodeChallengeMethod string                 `protobuf:"bytes,8,opt,name=code_challenge_method,json=codeChallengeMethod,proto3" json:"code_challenge_method,omitempty"`
	AcrValues           string                 `protobuf:"bytes,9,opt,name=acr_values,json=acrValues,proto3" json:"acr_values,omitempty"`
	Nonce               string                 `protobuf:"bytes,10,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// this is the internal code that will be returned to the OIDC client
	Code string `protobuf:"bytes,11,opt,name=code,proto3" json:"code,omitempty"`
	// IDPHint is the idp_hint of the external idp that the authorization must authenticate against
	IdpHint string `protobuf:"bytes,12,opt,name=idp_hint,json=idpHint,proto3" json:"idp_hint,omitempty"`
	// CandidateUserID is the user_id of the candidate user that if the external IDP has no link should be linked to
	// The candidate user must exist.
	CandidateUserId string `protobuf:"bytes,13,opt,name=candidate_user_id,json=candidateUserId,proto3" json:"candidate_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorizationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizationRequest) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *AuthorizationRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuthorizationRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizationRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizationRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *AuthorizationRequest) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

func (x *AuthorizationRequest) GetCodeChallengeMethod() string {
	if x != nil {
		return x.CodeChallengeMethod
	}
	return ""
}

func (x *AuthorizationRequest) GetAcrValues() string {
	if x != nil {
		return x.AcrValues
	}
	return ""
}

func (x *AuthorizationRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthorizationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthorizationRequest) GetIdpHint() string {
	if x != nil {
		return x.IdpHint
	}
	return ""
}

func (x *AuthorizationRequest) GetCandidateUserId() string {
	if x != nil {
		return x.CandidateUserId
	}
	return ""
}

type AuthorizationRequestState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id to make it db friendly
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Request          *AuthorizationRequest  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Identity         *OIDCIdentity          `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	ExternalIdentity *Identity              `protobuf:"bytes,4,opt,name=external_identity,json=externalIdentity,proto3" json:"external_identity,omitempty"`
	Directive        string                 `protobuf:"bytes,5,opt,name=directive,proto3" json:"directive,omitempty"`
	Updated          *timestamppb.Timestamp `protobuf:"bytes,51,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorizationRequestState) Reset() {
	*x = AuthorizationRequestState{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequestState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequestState) ProtoMessage() {}

func (x *AuthorizationRequestState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequestState.ProtoReflect.Descriptor instead.
func (*AuthorizationRequestState) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorizationRequestState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthorizationRequestState) GetRequest() *AuthorizationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuthorizationRequestState) GetIdentity() *OIDCIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *AuthorizationRequestState) GetExternalIdentity() *Identity {
	if x != nil {
		return x.ExternalIdentity
	}
	return nil
}

func (x *AuthorizationRequestState) GetDirective() string {
	if x != nil {
		return x.Directive
	}
	return ""
}

func (x *AuthorizationRequestState) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

type LinkedIdentities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedIdentities) Reset() {
	*x = LinkedIdentities{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedIdentities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedIdentities) ProtoMessage() {}

func (x *LinkedIdentities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedIdentities.ProtoReflect.Descriptor instead.
func (*LinkedIdentities) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{10}
}

func (x *LinkedIdentities) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type IdentityUpdate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Subject       string                  `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified *wrapperspb.BoolValue   `protobuf:"bytes,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityUpdate) Reset() {
	*x = IdentityUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityUpdate) ProtoMessage() {}

func (x *IdentityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityUpdate.ProtoReflect.Descriptor instead.
func (*IdentityUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{11}
}

func (x *IdentityUpdate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IdentityUpdate) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *IdentityUpdate) GetEmailVerified() *wrapperspb.BoolValue {
	if x != nil {
		return x.EmailVerified
	}
	return nil
}

type LinkedIdentitiesUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*LinkedIdentitiesUpdate_Granular_
	//	*LinkedIdentitiesUpdate_Replace
	Update        isLinkedIdentitiesUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedIdentitiesUpdate) Reset() {
	*x = LinkedIdentitiesUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedIdentitiesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedIdentitiesUpdate) ProtoMessage() {}

func (x *LinkedIdentitiesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedIdentitiesUpdate.ProtoReflect.Descriptor instead.
func (*LinkedIdentitiesUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{12}
}

func (x *LinkedIdentitiesUpdate) GetUpdate() isLinkedIdentitiesUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *LinkedIdentitiesUpdate) GetGranular() *LinkedIdentitiesUpdate_Granular {
	if x != nil {
		if x, ok := x.Update.(*LinkedIdentitiesUpdate_Granular_); ok {
			return x.Granular
		}
	}
	return nil
}

func (x *LinkedIdentitiesUpdate) GetReplace() *LinkedIdentities {
	if x != nil {
		if x, ok := x.Update.(*LinkedIdentitiesUpdate_Replace); ok {
			return x.Replace
		}
	}
	return nil
}

type isLinkedIdentitiesUpdate_Update interface {
	isLinkedIdentitiesUpdate_Update()
}

type LinkedIdentitiesUpdate_Granular_ struct {
	Granular *LinkedIdentitiesUpdate_Granular `protobuf:"bytes,1,opt,name=granular,proto3,oneof"`
}

type LinkedIdentitiesUpdate_Replace struct {
	Replace *LinkedIdentities `protobuf:"bytes,2,opt,name=replace,proto3,oneof"`
}

func (*LinkedIdentitiesUpdate_Granular_) isLinkedIdentitiesUpdate_Update() {}

func (*LinkedIdentitiesUpdate_Replace) isLinkedIdentitiesUpdate_Update() {}

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{13}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Email) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

type EmailUpdate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified *wrapperspb.BoolValue   `protobuf:"bytes,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailUpdate) Reset() {
	*x = EmailUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailUpdate) ProtoMessage() {}

func (x *EmailUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailUpdate.ProtoReflect.Descriptor instead.
func (*EmailUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{14}
}

func (x *EmailUpdate) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *EmailUpdate) GetEmailVerified() *wrapperspb.BoolValue {
	if x != nil {
		return x.EmailVerified
	}
	return nil
}

type Recovery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// only one email is allowed.  Make this simple
	Email         *Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recovery) Reset() {
	*x = Recovery{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recovery) ProtoMessage() {}

func (x *Recovery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recovery.ProtoReflect.Descriptor instead.
func (*Recovery) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{15}
}

func (x *Recovery) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type RecoveryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *EmailUpdate           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryUpdate) Reset() {
	*x = RecoveryUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryUpdate) ProtoMessage() {}

func (x *RecoveryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryUpdate.ProtoReflect.Descriptor instead.
func (*RecoveryUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{16}
}

func (x *RecoveryUpdate) GetEmail() *EmailUpdate {
	if x != nil {
		return x.Email
	}
	return nil
}

type WebAuthN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*webauthn.Credential `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthN) Reset() {
	*x = WebAuthN{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthN) ProtoMessage() {}

func (x *WebAuthN) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthN.ProtoReflect.Descriptor instead.
func (*WebAuthN) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{17}
}

func (x *WebAuthN) GetCredentials() []*webauthn.Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type WebAuthNUpdate struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Credentials   *webauthn.CredentialArrayUpdate `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthNUpdate) Reset() {
	*x = WebAuthNUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthNUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthNUpdate) ProtoMessage() {}

func (x *WebAuthNUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthNUpdate.ProtoReflect.Descriptor instead.
func (*WebAuthNUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{18}
}

func (x *WebAuthNUpdate) GetCredentials() *webauthn.CredentialArrayUpdate {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type TOTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Verified      bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTP) Reset() {
	*x = TOTP{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTP) ProtoMessage() {}

func (x *TOTP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTP.ProtoReflect.Descriptor instead.
func (*TOTP) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{19}
}

func (x *TOTP) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *TOTP) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TOTP) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type TOTPUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Verified      *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPUpdate) Reset() {
	*x = TOTPUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPUpdate) ProtoMessage() {}

func (x *TOTPUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPUpdate.ProtoReflect.Descriptor instead.
func (*TOTPUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{20}
}

func (x *TOTPUpdate) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *TOTPUpdate) GetVerified() *wrapperspb.BoolValue {
	if x != nil {
		return x.Verified
	}
	return nil
}

type RageUser struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	State            RageUserState          `protobuf:"varint,2,opt,name=state,proto3,enum=proto.oidc.models.RageUserState" json:"state,omitempty"`
	RootIdentity     *Identity              `protobuf:"bytes,3,opt,name=root_identity,json=rootIdentity,proto3" json:"root_identity,omitempty"`
	LinkedIdentities *LinkedIdentities      `protobuf:"bytes,4,opt,name=linked_identities,json=linkedIdentities,proto3" json:"linked_identities,omitempty"`
	Recovery         *Recovery              `protobuf:"bytes,5,opt,name=recovery,proto3" json:"recovery,omitempty"`
	Password         *Password              `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	WebAuthN         *WebAuthN              `protobuf:"bytes,7,opt,name=web_auth_n,json=webAuthN,proto3" json:"web_auth_n,omitempty"`
	TOTP             *TOTP                  `protobuf:"bytes,8,opt,name=t_o_t_p,json=tOTP,proto3" json:"t_o_t_p,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RageUser) Reset() {
	*x = RageUser{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RageUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RageUser) ProtoMessage() {}

func (x *RageUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RageUser.ProtoReflect.Descriptor instead.
func (*RageUser) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{21}
}

func (x *RageUser) GetState() RageUserState {
	if x != nil {
		return x.State
	}
	return RageUserState_USER_STATE_UNSPECIFIED
}

func (x *RageUser) GetRootIdentity() *Identity {
	if x != nil {
		return x.RootIdentity
	}
	return nil
}

func (x *RageUser) GetLinkedIdentities() *LinkedIdentities {
	if x != nil {
		return x.LinkedIdentities
	}
	return nil
}

func (x *RageUser) GetRecovery() *Recovery {
	if x != nil {
		return x.Recovery
	}
	return nil
}

func (x *RageUser) GetPassword() *Password {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *RageUser) GetWebAuthN() *WebAuthN {
	if x != nil {
		return x.WebAuthN
	}
	return nil
}

func (x *RageUser) GetTOTP() *TOTP {
	if x != nil {
		return x.TOTP
	}
	return nil
}

type RageUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*RageUser            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RageUsers) Reset() {
	*x = RageUsers{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RageUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RageUsers) ProtoMessage() {}

func (x *RageUsers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RageUsers.ProtoReflect.Descriptor instead.
func (*RageUsers) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{22}
}

func (x *RageUsers) GetUsers() []*RageUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type RageUserUpdate struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	RootIdentity     *IdentityUpdate         `protobuf:"bytes,1,opt,name=root_identity,json=rootIdentity,proto3" json:"root_identity,omitempty"`
	State            *RageUserStateValue     `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	LinkedIdentities *LinkedIdentitiesUpdate `protobuf:"bytes,3,opt,name=linked_identities,json=linkedIdentities,proto3" json:"linked_identities,omitempty"`
	Recovery         *RecoveryUpdate         `protobuf:"bytes,4,opt,name=recovery,proto3" json:"recovery,omitempty"`
	Password         *PasswordUpdate         `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	WebAuthN         *WebAuthNUpdate         `protobuf:"bytes,6,opt,name=web_auth_n,json=webAuthN,proto3" json:"web_auth_n,omitempty"`
	TOTP             *TOTPUpdate             `protobuf:"bytes,7,opt,name=t_o_t_p,json=tOTP,proto3" json:"t_o_t_p,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RageUserUpdate) Reset() {
	*x = RageUserUpdate{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RageUserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RageUserUpdate) ProtoMessage() {}

func (x *RageUserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RageUserUpdate.ProtoReflect.Descriptor instead.
func (*RageUserUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{23}
}

func (x *RageUserUpdate) GetRootIdentity() *IdentityUpdate {
	if x != nil {
		return x.RootIdentity
	}
	return nil
}

func (x *RageUserUpdate) GetState() *RageUserStateValue {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *RageUserUpdate) GetLinkedIdentities() *LinkedIdentitiesUpdate {
	if x != nil {
		return x.LinkedIdentities
	}
	return nil
}

func (x *RageUserUpdate) GetRecovery() *RecoveryUpdate {
	if x != nil {
		return x.Recovery
	}
	return nil
}

func (x *RageUserUpdate) GetPassword() *PasswordUpdate {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *RageUserUpdate) GetWebAuthN() *WebAuthNUpdate {
	if x != nil {
		return x.WebAuthN
	}
	return nil
}

func (x *RageUserUpdate) GetTOTP() *TOTPUpdate {
	if x != nil {
		return x.TOTP
	}
	return nil
}

type RageUserFilter struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	RootSubject           *types.IDFilterExpression     `protobuf:"bytes,1,opt,name=root_subject,json=rootSubject,proto3" json:"root_subject,omitempty"`
	RootIdpSlug           *types.IDFilterExpression     `protobuf:"bytes,2,opt,name=root_idp_slug,json=rootIdpSlug,proto3" json:"root_idp_slug,omitempty"`
	RootEmail             *types.StringFilterExpression `protobuf:"bytes,3,opt,name=root_email,json=rootEmail,proto3" json:"root_email,omitempty"`
	LinkedIdentitySubject *types.IDFilterExpression     `protobuf:"bytes,4,opt,name=linked_identity_subject,json=linkedIdentitySubject,proto3" json:"linked_identity_subject,omitempty"`
	LinkedIdentityIdpSlug *types.IDFilterExpression     `protobuf:"bytes,5,opt,name=linked_identity_idp_slug,json=linkedIdentityIdpSlug,proto3" json:"linked_identity_idp_slug,omitempty"`
	LinkedIdentityEmail   *types.StringFilterExpression `protobuf:"bytes,6,opt,name=linked_identity_email,json=linkedIdentityEmail,proto3" json:"linked_identity_email,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RageUserFilter) Reset() {
	*x = RageUserFilter{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RageUserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RageUserFilter) ProtoMessage() {}

func (x *RageUserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RageUserFilter.ProtoReflect.Descriptor instead.
func (*RageUserFilter) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{24}
}

func (x *RageUserFilter) GetRootSubject() *types.IDFilterExpression {
	if x != nil {
		return x.RootSubject
	}
	return nil
}

func (x *RageUserFilter) GetRootIdpSlug() *types.IDFilterExpression {
	if x != nil {
		return x.RootIdpSlug
	}
	return nil
}

func (x *RageUserFilter) GetRootEmail() *types.StringFilterExpression {
	if x != nil {
		return x.RootEmail
	}
	return nil
}

func (x *RageUserFilter) GetLinkedIdentitySubject() *types.IDFilterExpression {
	if x != nil {
		return x.LinkedIdentitySubject
	}
	return nil
}

func (x *RageUserFilter) GetLinkedIdentityIdpSlug() *types.IDFilterExpression {
	if x != nil {
		return x.LinkedIdentityIdpSlug
	}
	return nil
}

func (x *RageUserFilter) GetLinkedIdentityEmail() *types.StringFilterExpression {
	if x != nil {
		return x.LinkedIdentityEmail
	}
	return nil
}

type LinkedIdentitiesUpdate_Granular struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []*Identity            `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []*Identity            `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedIdentitiesUpdate_Granular) Reset() {
	*x = LinkedIdentitiesUpdate_Granular{}
	mi := &file_proto_oidc_models_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedIdentitiesUpdate_Granular) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedIdentitiesUpdate_Granular) ProtoMessage() {}

func (x *LinkedIdentitiesUpdate_Granular) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_models_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedIdentitiesUpdate_Granular.ProtoReflect.Descriptor instead.
func (*LinkedIdentitiesUpdate_Granular) Descriptor() ([]byte, []int) {
	return file_proto_oidc_models_user_proto_rawDescGZIP(), []int{12, 0}
}

func (x *LinkedIdentitiesUpdate_Granular) GetAdd() []*Identity {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *LinkedIdentitiesUpdate_Granular) GetRemove() []*Identity {
	if x != nil {
		return x.Remove
	}
	return nil
}

var File_proto_oidc_models_user_proto protoreflect.FileDescriptor

const file_proto_oidc_models_user_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/oidc/models/user.proto\x12\x11proto.oidc.models\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18proto/types/filter.proto\x1a#proto/types/webauthn/webauthn.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x12RageUserStateValue\x126\n" +
	"\x05value\x18\x01 \x01(\x0e2 .proto.oidc.models.RageUserStateR\x05value\"\x1e\n" +
	"\bPassword\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"B\n" +
	"\x0ePasswordUpdate\x120\n" +
	"\x04hash\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x04hash\"\xf2\x01\n" +
	"\bIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x19\n" +
	"\bidp_slug\x18\x02 \x01(\tR\aidpSlug\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x129\n" +
	"\n" +
	"created_on\x182 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\x129\n" +
	"\n" +
	"updated_on\x183 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedOn\"\xc2\x01\n" +
	"\x0eIdentityFilter\x129\n" +
	"\asubject\x18\x01 \x01(\v2\x1f.proto.types.IDFilterExpressionR\asubject\x12:\n" +
	"\bidp_slug\x18\x02 \x01(\v2\x1f.proto.types.IDFilterExpressionR\aidpSlug\x129\n" +
	"\x05email\x18\x03 \x01(\v2#.proto.types.StringFilterExpressionR\x05email\"\xa4\x01\n" +
	"\fOIDCIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x19\n" +
	"\bidp_slug\x18\x02 \x01(\tR\aidpSlug\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x12\x10\n" +
	"\x03acr\x18\x05 \x03(\tR\x03acr\x12\x10\n" +
	"\x03amr\x18\x06 \x03(\tR\x03amr\"\xcf\x02\n" +
	"\x15ExternalOauth2Request\x12\x19\n" +
	"\bidp_hint\x18\x01 \x01(\tR\aidpHint\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x0ecode_challenge\x18\x03 \x01(\tR\rcodeChallenge\x122\n" +
	"\x15code_challenge_method\x18\x04 \x01(\tR\x13codeChallengeMethod\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x126\n" +
	"\x17code_challenge_verifier\x18\x06 \x01(\tR\x15codeChallengeVerifier\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x1c\n" +
	"\tdirective\x18\b \x01(\tR\tdirective\x12!\n" +
	"\fparent_state\x18\t \x01(\tR\vparentState\"\x92\x01\n" +
	"\x13ExternalOauth2State\x12B\n" +
	"\arequest\x18\x01 \x01(\v2(.proto.oidc.models.ExternalOauth2RequestR\arequest\x127\n" +
	"\bidentity\x18\x02 \x01(\v2\x1b.proto.oidc.models.IdentityR\bidentity\"\xae\x03\n" +
	"\x14AuthorizationRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rresponse_type\x18\x02 \x01(\tR\fresponseType\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12!\n" +
	"\fredirect_uri\x18\x05 \x01(\tR\vredirectUri\x12\x1a\n" +
	"\baudience\x18\x06 \x01(\tR\baudience\x12%\n" +
	"\x0ecode_challenge\x18\a \x01(\tR\rcodeChallenge\x122\n" +
	"\x15code_challenge_method\x18\b \x01(\tR\x13codeChallengeMethod\x12\x1d\n" +
	"\n" +
	"acr_values\x18\t \x01(\tR\tacrValues\x12\x14\n" +
	"\x05nonce\x18\n" +
	" \x01(\tR\x05nonce\x12\x12\n" +
	"\x04code\x18\v \x01(\tR\x04code\x12\x19\n" +
	"\bidp_hint\x18\f \x01(\tR\aidpHint\x12*\n" +
	"\x11candidate_user_id\x18\r \x01(\tR\x0fcandidateUserId\"\xc9\x02\n" +
	"\x19AuthorizationRequestState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\arequest\x18\x02 \x01(\v2'.proto.oidc.models.AuthorizationRequestR\arequest\x12;\n" +
	"\bidentity\x18\x03 \x01(\v2\x1f.proto.oidc.models.OIDCIdentityR\bidentity\x12H\n" +
	"\x11external_identity\x18\x04 \x01(\v2\x1b.proto.oidc.models.IdentityR\x10externalIdentity\x12\x1c\n" +
	"\tdirective\x18\x05 \x01(\tR\tdirective\x124\n" +
	"\aupdated\x183 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\"O\n" +
	"\x10LinkedIdentities\x12;\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x1b.proto.oidc.models.IdentityR\n" +
	"identities\"\xa1\x01\n" +
	"\x0eIdentityUpdate\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x122\n" +
	"\x05email\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x12A\n" +
	"\x0eemail_verified\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\remailVerified\"\xa5\x02\n" +
	"\x16LinkedIdentitiesUpdate\x12P\n" +
	"\bgranular\x18\x01 \x01(\v22.proto.oidc.models.LinkedIdentitiesUpdate.GranularH\x00R\bgranular\x12?\n" +
	"\areplace\x18\x02 \x01(\v2#.proto.oidc.models.LinkedIdentitiesH\x00R\areplace\x1an\n" +
	"\bGranular\x12-\n" +
	"\x03add\x18\x01 \x03(\v2\x1b.proto.oidc.models.IdentityR\x03add\x123\n" +
	"\x06remove\x18\x02 \x03(\v2\x1b.proto.oidc.models.IdentityR\x06removeB\b\n" +
	"\x06update\"D\n" +
	"\x05Email\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x02 \x01(\bR\remailVerified\"\x84\x01\n" +
	"\vEmailUpdate\x122\n" +
	"\x05email\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x12A\n" +
	"\x0eemail_verified\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\remailVerified\":\n" +
	"\bRecovery\x12.\n" +
	"\x05email\x18\x01 \x01(\v2\x18.proto.oidc.models.EmailR\x05email\"F\n" +
	"\x0eRecoveryUpdate\x124\n" +
	"\x05email\x18\x01 \x01(\v2\x1e.proto.oidc.models.EmailUpdateR\x05email\"N\n" +
	"\bWebAuthN\x12B\n" +
	"\vcredentials\x18\x01 \x03(\v2 .proto.types.webauthn.CredentialR\vcredentials\"_\n" +
	"\x0eWebAuthNUpdate\x12M\n" +
	"\vcredentials\x18\x01 \x01(\v2+.proto.types.webauthn.CredentialArrayUpdateR\vcredentials\"T\n" +
	"\x04TOTP\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\"z\n" +
	"\n" +
	"TOTPUpdate\x124\n" +
	"\aenabled\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\aenabled\x126\n" +
	"\bverified\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\bverified\"\xb3\x03\n" +
	"\bRageUser\x126\n" +
	"\x05state\x18\x02 \x01(\x0e2 .proto.oidc.models.RageUserStateR\x05state\x12@\n" +
	"\rroot_identity\x18\x03 \x01(\v2\x1b.proto.oidc.models.IdentityR\frootIdentity\x12P\n" +
	"\x11linked_identities\x18\x04 \x01(\v2#.proto.oidc.models.LinkedIdentitiesR\x10linkedIdentities\x127\n" +
	"\brecovery\x18\x05 \x01(\v2\x1b.proto.oidc.models.RecoveryR\brecovery\x127\n" +
	"\bpassword\x18\x06 \x01(\v2\x1b.proto.oidc.models.PasswordR\bpassword\x129\n" +
	"\n" +
	"web_auth_n\x18\a \x01(\v2\x1b.proto.oidc.models.WebAuthNR\bwebAuthN\x12.\n" +
	"\at_o_t_p\x18\b \x01(\v2\x17.proto.oidc.models.TOTPR\x04tOTP\">\n" +
	"\tRageUsers\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.proto.oidc.models.RageUserR\x05users\"\xe2\x03\n" +
	"\x0eRageUserUpdate\x12F\n" +
	"\rroot_identity\x18\x01 \x01(\v2!.proto.oidc.models.IdentityUpdateR\frootIdentity\x12;\n" +
	"\x05state\x18\x02 \x01(\v2%.proto.oidc.models.RageUserStateValueR\x05state\x12V\n" +
	"\x11linked_identities\x18\x03 \x01(\v2).proto.oidc.models.LinkedIdentitiesUpdateR\x10linkedIdentities\x12=\n" +
	"\brecovery\x18\x04 \x01(\v2!.proto.oidc.models.RecoveryUpdateR\brecovery\x12=\n" +
	"\bpassword\x18\x05 \x01(\v2!.proto.oidc.models.PasswordUpdateR\bpassword\x12?\n" +
	"\n" +
	"web_auth_n\x18\x06 \x01(\v2!.proto.oidc.models.WebAuthNUpdateR\bwebAuthN\x124\n" +
	"\at_o_t_p\x18\a \x01(\v2\x1d.proto.oidc.models.TOTPUpdateR\x04tOTP\"\xe9\x03\n" +
	"\x0eRageUserFilter\x12B\n" +
	"\froot_subject\x18\x01 \x01(\v2\x1f.proto.types.IDFilterExpressionR\vrootSubject\x12C\n" +
	"\rroot_idp_slug\x18\x02 \x01(\v2\x1f.proto.types.IDFilterExpressionR\vrootIdpSlug\x12B\n" +
	"\n" +
	"root_email\x18\x03 \x01(\v2#.proto.types.StringFilterExpressionR\trootEmail\x12W\n" +
	"\x17linked_identity_subject\x18\x04 \x01(\v2\x1f.proto.types.IDFilterExpressionR\x15linkedIdentitySubject\x12X\n" +
	"\x18linked_identity_idp_slug\x18\x05 \x01(\v2\x1f.proto.types.IDFilterExpressionR\x15linkedIdentityIdpSlug\x12W\n" +
	"\x15linked_identity_email\x18\x06 \x01(\v2#.proto.types.StringFilterExpressionR\x13linkedIdentityEmail*\x8b\x01\n" +
	"\rRageUserState\x12\x1a\n" +
	"\x16USER_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11USER_STATE_ACTIVE\x10\x01\x12\x17\n" +
	"\x13USER_STATE_DISABLED\x10\x02\x12\x16\n" +
	"\x12USER_STATE_DELETED\x10\x03\x12\x16\n" +
	"\x12USER_STATE_PENDING\x10\x04BKZIgithub.com/fluffy-bunny/fluffycore-rage-identity/proto/oidc/models;modelsb\x06proto3"

var (
	file_proto_oidc_models_user_proto_rawDescOnce sync.Once
	file_proto_oidc_models_user_proto_rawDescData []byte
)

func file_proto_oidc_models_user_proto_rawDescGZIP() []byte {
	file_proto_oidc_models_user_proto_rawDescOnce.Do(func() {
		file_proto_oidc_models_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oidc_models_user_proto_rawDesc), len(file_proto_oidc_models_user_proto_rawDesc)))
	})
	return file_proto_oidc_models_user_proto_rawDescData
}

var file_proto_oidc_models_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_oidc_models_user_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_oidc_models_user_proto_goTypes = []any{
	(RageUserState)(0),                      // 0: proto.oidc.models.RageUserState
	(*RageUserStateValue)(nil),              // 1: proto.oidc.models.RageUserStateValue
	(*Password)(nil),                        // 2: proto.oidc.models.Password
	(*PasswordUpdate)(nil),                  // 3: proto.oidc.models.PasswordUpdate
	(*Identity)(nil),                        // 4: proto.oidc.models.Identity
	(*IdentityFilter)(nil),                  // 5: proto.oidc.models.IdentityFilter
	(*OIDCIdentity)(nil),                    // 6: proto.oidc.models.OIDCIdentity
	(*ExternalOauth2Request)(nil),           // 7: proto.oidc.models.ExternalOauth2Request
	(*ExternalOauth2State)(nil),             // 8: proto.oidc.models.ExternalOauth2State
	(*AuthorizationRequest)(nil),            // 9: proto.oidc.models.AuthorizationRequest
	(*AuthorizationRequestState)(nil),       // 10: proto.oidc.models.AuthorizationRequestState
	(*LinkedIdentities)(nil),                // 11: proto.oidc.models.LinkedIdentities
	(*IdentityUpdate)(nil),                  // 12: proto.oidc.models.IdentityUpdate
	(*LinkedIdentitiesUpdate)(nil),          // 13: proto.oidc.models.LinkedIdentitiesUpdate
	(*Email)(nil),                           // 14: proto.oidc.models.Email
	(*EmailUpdate)(nil),                     // 15: proto.oidc.models.EmailUpdate
	(*Recovery)(nil),                        // 16: proto.oidc.models.Recovery
	(*RecoveryUpdate)(nil),                  // 17: proto.oidc.models.RecoveryUpdate
	(*WebAuthN)(nil),                        // 18: proto.oidc.models.WebAuthN
	(*WebAuthNUpdate)(nil),                  // 19: proto.oidc.models.WebAuthNUpdate
	(*TOTP)(nil),                            // 20: proto.oidc.models.TOTP
	(*TOTPUpdate)(nil),                      // 21: proto.oidc.models.TOTPUpdate
	(*RageUser)(nil),                        // 22: proto.oidc.models.RageUser
	(*RageUsers)(nil),                       // 23: proto.oidc.models.RageUsers
	(*RageUserUpdate)(nil),                  // 24: proto.oidc.models.RageUserUpdate
	(*RageUserFilter)(nil),                  // 25: proto.oidc.models.RageUserFilter
	(*LinkedIdentitiesUpdate_Granular)(nil), // 26: proto.oidc.models.LinkedIdentitiesUpdate.Granular
	(*wrapperspb.StringValue)(nil),          // 27: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),           // 28: google.protobuf.Timestamp
	(*types.IDFilterExpression)(nil),        // 29: proto.types.IDFilterExpression
	(*types.StringFilterExpression)(nil),    // 30: proto.types.StringFilterExpression
	(*wrapperspb.BoolValue)(nil),            // 31: google.protobuf.BoolValue
	(*webauthn.Credential)(nil),             // 32: proto.types.webauthn.Credential
	(*webauthn.CredentialArrayUpdate)(nil),  // 33: proto.types.webauthn.CredentialArrayUpdate
}
var file_proto_oidc_models_user_proto_depIdxs = []int32{
	0,  // 0: proto.oidc.models.RageUserStateValue.value:type_name -> proto.oidc.models.RageUserState
	27, // 1: proto.oidc.models.PasswordUpdate.hash:type_name -> google.protobuf.StringValue
	28, // 2: proto.oidc.models.Identity.created_on:type_name -> google.protobuf.Timestamp
	28, // 3: proto.oidc.models.Identity.updated_on:type_name -> google.protobuf.Timestamp
	29, // 4: proto.oidc.models.IdentityFilter.subject:type_name -> proto.types.IDFilterExpression
	29, // 5: proto.oidc.models.IdentityFilter.idp_slug:type_name -> proto.types.IDFilterExpression
	30, // 6: proto.oidc.models.IdentityFilter.email:type_name -> proto.types.StringFilterExpression
	7,  // 7: proto.oidc.models.ExternalOauth2State.request:type_name -> proto.oidc.models.ExternalOauth2Request
	4,  // 8: proto.oidc.models.ExternalOauth2State.identity:type_name -> proto.oidc.models.Identity
	9,  // 9: proto.oidc.models.AuthorizationRequestState.request:type_name -> proto.oidc.models.AuthorizationRequest
	6,  // 10: proto.oidc.models.AuthorizationRequestState.identity:type_name -> proto.oidc.models.OIDCIdentity
	4,  // 11: proto.oidc.models.AuthorizationRequestState.external_identity:type_name -> proto.oidc.models.Identity
	28, // 12: proto.oidc.models.AuthorizationRequestState.updated:type_name -> google.protobuf.Timestamp
	4,  // 13: proto.oidc.models.LinkedIdentities.identities:type_name -> proto.oidc.models.Identity
	27, // 14: proto.oidc.models.IdentityUpdate.email:type_name -> google.protobuf.StringValue
	31, // 15: proto.oidc.models.IdentityUpdate.email_verified:type_name -> google.protobuf.BoolValue
	26, // 16: proto.oidc.models.LinkedIdentitiesUpdate.granular:type_name -> proto.oidc.models.LinkedIdentitiesUpdate.Granular
	11, // 17: proto.oidc.models.LinkedIdentitiesUpdate.replace:type_name -> proto.oidc.models.LinkedIdentities
	27, // 18: proto.oidc.models.EmailUpdate.email:type_name -> google.protobuf.StringValue
	31, // 19: proto.oidc.models.EmailUpdate.email_verified:type_name -> google.protobuf.BoolValue
	14, // 20: proto.oidc.models.Recovery.email:type_name -> proto.oidc.models.Email
	15, // 21: proto.oidc.models.RecoveryUpdate.email:type_name -> proto.oidc.models.EmailUpdate
	32, // 22: proto.oidc.models.WebAuthN.credentials:type_name -> proto.types.webauthn.Credential
	33, // 23: proto.oidc.models.WebAuthNUpdate.credentials:type_name -> proto.types.webauthn.CredentialArrayUpdate
	31, // 24: proto.oidc.models.TOTPUpdate.enabled:type_name -> google.protobuf.BoolValue
	31, // 25: proto.oidc.models.TOTPUpdate.verified:type_name -> google.protobuf.BoolValue
	0,  // 26: proto.oidc.models.RageUser.state:type_name -> proto.oidc.models.RageUserState
	4,  // 27: proto.oidc.models.RageUser.root_identity:type_name -> proto.oidc.models.Identity
	11, // 28: proto.oidc.models.RageUser.linked_identities:type_name -> proto.oidc.models.LinkedIdentities
	16, // 29: proto.oidc.models.RageUser.recovery:type_name -> proto.oidc.models.Recovery
	2,  // 30: proto.oidc.models.RageUser.password:type_name -> proto.oidc.models.Password
	18, // 31: proto.oidc.models.RageUser.web_auth_n:type_name -> proto.oidc.models.WebAuthN
	20, // 32: proto.oidc.models.RageUser.t_o_t_p:type_name -> proto.oidc.models.TOTP
	22, // 33: proto.oidc.models.RageUsers.users:type_name -> proto.oidc.models.RageUser
	12, // 34: proto.oidc.models.RageUserUpdate.root_identity:type_name -> proto.oidc.models.IdentityUpdate
	1,  // 35: proto.oidc.models.RageUserUpdate.state:type_name -> proto.oidc.models.RageUserStateValue
	13, // 36: proto.oidc.models.RageUserUpdate.linked_identities:type_name -> proto.oidc.models.LinkedIdentitiesUpdate
	17, // 37: proto.oidc.models.RageUserUpdate.recovery:type_name -> proto.oidc.models.RecoveryUpdate
	3,  // 38: proto.oidc.models.RageUserUpdate.password:type_name -> proto.oidc.models.PasswordUpdate
	19, // 39: proto.oidc.models.RageUserUpdate.web_auth_n:type_name -> proto.oidc.models.WebAuthNUpdate
	21, // 40: proto.oidc.models.RageUserUpdate.t_o_t_p:type_name -> proto.oidc.models.TOTPUpdate
	29, // 41: proto.oidc.models.RageUserFilter.root_subject:type_name -> proto.types.IDFilterExpression
	29, // 42: proto.oidc.models.RageUserFilter.root_idp_slug:type_name -> proto.types.IDFilterExpression
	30, // 43: proto.oidc.models.RageUserFilter.root_email:type_name -> proto.types.StringFilterExpression
	29, // 44: proto.oidc.models.RageUserFilter.linked_identity_subject:type_name -> proto.types.IDFilterExpression
	29, // 45: proto.oidc.models.RageUserFilter.linked_identity_idp_slug:type_name -> proto.types.IDFilterExpression
	30, // 46: proto.oidc.models.RageUserFilter.linked_identity_email:type_name -> proto.types.StringFilterExpression
	4,  // 47: proto.oidc.models.LinkedIdentitiesUpdate.Granular.add:type_name -> proto.oidc.models.Identity
	4,  // 48: proto.oidc.models.LinkedIdentitiesUpdate.Granular.remove:type_name -> proto.oidc.models.Identity
	49, // [49:49] is the sub-list for method output_type
	49, // [49:49] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_proto_oidc_models_user_proto_init() }
func file_proto_oidc_models_user_proto_init() {
	if File_proto_oidc_models_user_proto != nil {
		return
	}
	file_proto_oidc_models_user_proto_msgTypes[12].OneofWrappers = []any{
		(*LinkedIdentitiesUpdate_Granular_)(nil),
		(*LinkedIdentitiesUpdate_Replace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oidc_models_user_proto_rawDesc), len(file_proto_oidc_models_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_oidc_models_user_proto_goTypes,
		DependencyIndexes: file_proto_oidc_models_user_proto_depIdxs,
		EnumInfos:         file_proto_oidc_models_user_proto_enumTypes,
		MessageInfos:      file_proto_oidc_models_user_proto_msgTypes,
	}.Build()
	File_proto_oidc_models_user_proto = out.File
	file_proto_oidc_models_user_proto_goTypes = nil
	file_proto_oidc_models_user_proto_depIdxs = nil
}
