// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/oidc/client/client.proto

package client

import (
	models "github.com/fluffy-bunny/fluffycore-rage-identity/proto/oidc/models"
	types "github.com/fluffy-bunny/fluffycore-rage-identity/proto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state                                   protoimpl.MessageState             `protogen:"open.v1"`
	ClientId                                *types.IDFilterExpression          `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Enabled                                 *types.BoolFilterExpression        `protobuf:"bytes,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ClientName                              *types.StringFilterExpression      `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Description                             *types.StringFilterExpression      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Namespace                               *types.StringFilterExpression      `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RequireRefreshClientSecret              *types.BoolFilterExpression        `protobuf:"bytes,6,opt,name=require_refresh_client_secret,json=requireRefreshClientSecret,proto3" json:"require_refresh_client_secret,omitempty"`
	AllowOfflineAccess                      *types.BoolFilterExpression        `protobuf:"bytes,7,opt,name=allow_offline_access,json=allowOfflineAccess,proto3" json:"allow_offline_access,omitempty"`
	UpdateAccessTokenClaimsOnRefresh        *types.BoolFilterExpression        `protobuf:"bytes,8,opt,name=update_access_token_claims_on_refresh,json=updateAccessTokenClaimsOnRefresh,proto3" json:"update_access_token_claims_on_refresh,omitempty"`
	IncludeJwtId                            *types.BoolFilterExpression        `protobuf:"bytes,9,opt,name=include_jwt_id,json=includeJwtId,proto3" json:"include_jwt_id,omitempty"`
	AlwaysSendClientClaims                  *types.BoolFilterExpression        `protobuf:"bytes,10,opt,name=always_send_client_claims,json=alwaysSendClientClaims,proto3" json:"always_send_client_claims,omitempty"`
	AlwaysIncludeUserClaimsInIdToken        *types.BoolFilterExpression        `protobuf:"bytes,11,opt,name=always_include_user_claims_in_id_token,json=alwaysIncludeUserClaimsInIdToken,proto3" json:"always_include_user_claims_in_id_token,omitempty"`
	RequireClientSecret                     *types.BoolFilterExpression        `protobuf:"bytes,12,opt,name=require_client_secret,json=requireClientSecret,proto3" json:"require_client_secret,omitempty"`
	AccessTokenLifetime                     *types.UInt64FilterExpression      `protobuf:"bytes,13,opt,name=access_token_lifetime,json=accessTokenLifetime,proto3" json:"access_token_lifetime,omitempty"`
	AbsoluteRefreshTokenLifetime            *types.UInt64FilterExpression      `protobuf:"bytes,14,opt,name=absolute_refresh_token_lifetime,json=absoluteRefreshTokenLifetime,proto3" json:"absolute_refresh_token_lifetime,omitempty"`
	SlidingRefreshTokenLifetime             *types.UInt64FilterExpression      `protobuf:"bytes,15,opt,name=sliding_refresh_token_lifetime,json=slidingRefreshTokenLifetime,proto3" json:"sliding_refresh_token_lifetime,omitempty"`
	IdentityTokenLifetime                   *types.UInt64FilterExpression      `protobuf:"bytes,16,opt,name=identity_token_lifetime,json=identityTokenLifetime,proto3" json:"identity_token_lifetime,omitempty"`
	RefreshTokenGraceEnabled                *types.BoolFilterExpression        `protobuf:"bytes,17,opt,name=refresh_token_grace_enabled,json=refreshTokenGraceEnabled,proto3" json:"refresh_token_grace_enabled,omitempty"`
	RefreshTokenGraceTtl                    *types.UInt64FilterExpression      `protobuf:"bytes,18,opt,name=refresh_token_grace_ttl,json=refreshTokenGraceTtl,proto3" json:"refresh_token_grace_ttl,omitempty"`
	RefreshTokenGraceMaxAttempts            *types.UInt64FilterExpression      `protobuf:"bytes,19,opt,name=refresh_token_grace_max_attempts,json=refreshTokenGraceMaxAttempts,proto3" json:"refresh_token_grace_max_attempts,omitempty"`
	RefreshTokenUsage                       *types.UInt64FilterExpression      `protobuf:"bytes,20,opt,name=refresh_token_usage,json=refreshTokenUsage,proto3" json:"refresh_token_usage,omitempty"`
	RefreshTokenExpiration                  *types.UInt64FilterExpression      `protobuf:"bytes,21,opt,name=refresh_token_expiration,json=refreshTokenExpiration,proto3" json:"refresh_token_expiration,omitempty"`
	AccessTokenType                         *types.UInt64FilterExpression      `protobuf:"bytes,22,opt,name=access_token_type,json=accessTokenType,proto3" json:"access_token_type,omitempty"`
	AllowedScopes                           *types.StringArrayFilterExpression `protobuf:"bytes,24,opt,name=allowed_scopes,json=allowedScopes,proto3" json:"allowed_scopes,omitempty"`
	AllowedGrantTypes                       *types.StringArrayFilterExpression `protobuf:"bytes,25,opt,name=allowed_grant_types,json=allowedGrantTypes,proto3" json:"allowed_grant_types,omitempty"`
	AllowedPermissions                      *types.StringArrayFilterExpression `protobuf:"bytes,27,opt,name=allowed_permissions,json=allowedPermissions,proto3" json:"allowed_permissions,omitempty"`
	AllowedDynamicClaimTypes                *types.StringArrayFilterExpression `protobuf:"bytes,28,opt,name=allowed_dynamic_claim_types,json=allowedDynamicClaimTypes,proto3" json:"allowed_dynamic_claim_types,omitempty"`
	AllowedTokenExchangeRequestedTokenTypes *types.StringArrayFilterExpression `protobuf:"bytes,29,opt,name=allowed_token_exchange_requested_token_types,json=allowedTokenExchangeRequestedTokenTypes,proto3" json:"allowed_token_exchange_requested_token_types,omitempty"`
	// AST
	And           []*Filter `protobuf:"bytes,100,rep,name=and,proto3" json:"and,omitempty"`
	Or            []*Filter `protobuf:"bytes,101,rep,name=or,proto3" json:"or,omitempty"`
	Not           []*Filter `protobuf:"bytes,102,rep,name=not,proto3" json:"not,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetClientId() *types.IDFilterExpression {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *Filter) GetEnabled() *types.BoolFilterExpression {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *Filter) GetClientName() *types.StringFilterExpression {
	if x != nil {
		return x.ClientName
	}
	return nil
}

func (x *Filter) GetDescription() *types.StringFilterExpression {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Filter) GetNamespace() *types.StringFilterExpression {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Filter) GetRequireRefreshClientSecret() *types.BoolFilterExpression {
	if x != nil {
		return x.RequireRefreshClientSecret
	}
	return nil
}

func (x *Filter) GetAllowOfflineAccess() *types.BoolFilterExpression {
	if x != nil {
		return x.AllowOfflineAccess
	}
	return nil
}

func (x *Filter) GetUpdateAccessTokenClaimsOnRefresh() *types.BoolFilterExpression {
	if x != nil {
		return x.UpdateAccessTokenClaimsOnRefresh
	}
	return nil
}

func (x *Filter) GetIncludeJwtId() *types.BoolFilterExpression {
	if x != nil {
		return x.IncludeJwtId
	}
	return nil
}

func (x *Filter) GetAlwaysSendClientClaims() *types.BoolFilterExpression {
	if x != nil {
		return x.AlwaysSendClientClaims
	}
	return nil
}

func (x *Filter) GetAlwaysIncludeUserClaimsInIdToken() *types.BoolFilterExpression {
	if x != nil {
		return x.AlwaysIncludeUserClaimsInIdToken
	}
	return nil
}

func (x *Filter) GetRequireClientSecret() *types.BoolFilterExpression {
	if x != nil {
		return x.RequireClientSecret
	}
	return nil
}

func (x *Filter) GetAccessTokenLifetime() *types.UInt64FilterExpression {
	if x != nil {
		return x.AccessTokenLifetime
	}
	return nil
}

func (x *Filter) GetAbsoluteRefreshTokenLifetime() *types.UInt64FilterExpression {
	if x != nil {
		return x.AbsoluteRefreshTokenLifetime
	}
	return nil
}

func (x *Filter) GetSlidingRefreshTokenLifetime() *types.UInt64FilterExpression {
	if x != nil {
		return x.SlidingRefreshTokenLifetime
	}
	return nil
}

func (x *Filter) GetIdentityTokenLifetime() *types.UInt64FilterExpression {
	if x != nil {
		return x.IdentityTokenLifetime
	}
	return nil
}

func (x *Filter) GetRefreshTokenGraceEnabled() *types.BoolFilterExpression {
	if x != nil {
		return x.RefreshTokenGraceEnabled
	}
	return nil
}

func (x *Filter) GetRefreshTokenGraceTtl() *types.UInt64FilterExpression {
	if x != nil {
		return x.RefreshTokenGraceTtl
	}
	return nil
}

func (x *Filter) GetRefreshTokenGraceMaxAttempts() *types.UInt64FilterExpression {
	if x != nil {
		return x.RefreshTokenGraceMaxAttempts
	}
	return nil
}

func (x *Filter) GetRefreshTokenUsage() *types.UInt64FilterExpression {
	if x != nil {
		return x.RefreshTokenUsage
	}
	return nil
}

func (x *Filter) GetRefreshTokenExpiration() *types.UInt64FilterExpression {
	if x != nil {
		return x.RefreshTokenExpiration
	}
	return nil
}

func (x *Filter) GetAccessTokenType() *types.UInt64FilterExpression {
	if x != nil {
		return x.AccessTokenType
	}
	return nil
}

func (x *Filter) GetAllowedScopes() *types.StringArrayFilterExpression {
	if x != nil {
		return x.AllowedScopes
	}
	return nil
}

func (x *Filter) GetAllowedGrantTypes() *types.StringArrayFilterExpression {
	if x != nil {
		return x.AllowedGrantTypes
	}
	return nil
}

func (x *Filter) GetAllowedPermissions() *types.StringArrayFilterExpression {
	if x != nil {
		return x.AllowedPermissions
	}
	return nil
}

func (x *Filter) GetAllowedDynamicClaimTypes() *types.StringArrayFilterExpression {
	if x != nil {
		return x.AllowedDynamicClaimTypes
	}
	return nil
}

func (x *Filter) GetAllowedTokenExchangeRequestedTokenTypes() *types.StringArrayFilterExpression {
	if x != nil {
		return x.AllowedTokenExchangeRequestedTokenTypes
	}
	return nil
}

func (x *Filter) GetAnd() []*Filter {
	if x != nil {
		return x.And
	}
	return nil
}

func (x *Filter) GetOr() []*Filter {
	if x != nil {
		return x.Or
	}
	return nil
}

func (x *Filter) GetNot() []*Filter {
	if x != nil {
		return x.Not
	}
	return nil
}

type ValidateClientSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client id
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// secret
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientSecretRequest) Reset() {
	*x = ValidateClientSecretRequest{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientSecretRequest) ProtoMessage() {}

func (x *ValidateClientSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientSecretRequest.ProtoReflect.Descriptor instead.
func (*ValidateClientSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateClientSecretRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ValidateClientSecretRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ValidateClientSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientSecretResponse) Reset() {
	*x = ValidateClientSecretResponse{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientSecretResponse) ProtoMessage() {}

func (x *ValidateClientSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientSecretResponse.ProtoReflect.Descriptor instead.
func (*ValidateClientSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateClientSecretResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type AddNewClientSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client id
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The secret name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// expiration of the secret
	ExpirationUnix int64 `protobuf:"varint,3,opt,name=expiration_unix,json=expirationUnix,proto3" json:"expiration_unix,omitempty"`
	// the secret vs a generated secret
	Secret        *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNewClientSecretRequest) Reset() {
	*x = AddNewClientSecretRequest{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNewClientSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewClientSecretRequest) ProtoMessage() {}

func (x *AddNewClientSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewClientSecretRequest.ProtoReflect.Descriptor instead.
func (*AddNewClientSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{3}
}

func (x *AddNewClientSecretRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AddNewClientSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddNewClientSecretRequest) GetExpirationUnix() int64 {
	if x != nil {
		return x.ExpirationUnix
	}
	return 0
}

func (x *AddNewClientSecretRequest) GetSecret() *wrapperspb.StringValue {
	if x != nil {
		return x.Secret
	}
	return nil
}

type AddNewClientSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client id
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The secret name
	ClientSecret  *models.ClientSecretResponse `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNewClientSecretResponse) Reset() {
	*x = AddNewClientSecretResponse{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNewClientSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewClientSecretResponse) ProtoMessage() {}

func (x *AddNewClientSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewClientSecretResponse.ProtoReflect.Descriptor instead.
func (*AddNewClientSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{4}
}

func (x *AddNewClientSecretResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AddNewClientSecretResponse) GetClientSecret() *models.ClientSecretResponse {
	if x != nil {
		return x.ClientSecret
	}
	return nil
}

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *models.Client         `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{5}
}

func (x *CreateClientRequest) GetClient() *models.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *models.Client         `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{6}
}

func (x *CreateClientResponse) GetClient() *models.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{7}
}

func (x *GetClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *models.Client         `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientResponse) Reset() {
	*x = GetClientResponse{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientResponse) ProtoMessage() {}

func (x *GetClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientResponse.ProtoReflect.Descriptor instead.
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{8}
}

func (x *GetClientResponse) GetClient() *models.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{10}
}

type UpdateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *models.ClientUpdate   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateClientRequest) GetClient() *models.ClientUpdate {
	if x != nil {
		return x.Client
	}
	return nil
}

type UpdateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *models.Client         `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientResponse) Reset() {
	*x = UpdateClientResponse{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientResponse) ProtoMessage() {}

func (x *UpdateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateClientResponse) GetClient() *models.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type ListClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter
	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Pagination
	Pagination    *types.Pagination `protobuf:"bytes,100,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientRequest) Reset() {
	*x = ListClientRequest{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientRequest) ProtoMessage() {}

func (x *ListClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientRequest.ProtoReflect.Descriptor instead.
func (*ListClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{13}
}

func (x *ListClientRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListClientRequest) GetPagination() *types.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListClientResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Clients []*models.Client       `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	// Pagination details
	Pagination    *types.PaginationResponse `protobuf:"bytes,100,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientResponse) Reset() {
	*x = ListClientResponse{}
	mi := &file_proto_oidc_client_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientResponse) ProtoMessage() {}

func (x *ListClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_client_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientResponse.ProtoReflect.Descriptor instead.
func (*ListClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_client_client_proto_rawDescGZIP(), []int{14}
}

func (x *ListClientResponse) GetClients() []*models.Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ListClientResponse) GetPagination() *types.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_proto_oidc_client_client_proto protoreflect.FileDescriptor

const file_proto_oidc_client_client_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/oidc/client/client.proto\x12\x11proto.oidc.client\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18proto/types/filter.proto\x1a\x1cproto/types/pagination.proto\x1a\x1eproto/oidc/models/client.proto\x1a\x1cgoogle/api/annotations.proto\"\xaf\x14\n" +
	"\x06Filter\x12<\n" +
	"\tclient_id\x18\x01 \x01(\v2\x1f.proto.types.IDFilterExpressionR\bclientId\x12;\n" +
	"\aenabled\x18\x02 \x01(\v2!.proto.types.BoolFilterExpressionR\aenabled\x12D\n" +
	"\vclient_name\x18\x03 \x01(\v2#.proto.types.StringFilterExpressionR\n" +
	"clientName\x12E\n" +
	"\vdescription\x18\x04 \x01(\v2#.proto.types.StringFilterExpressionR\vdescription\x12A\n" +
	"\tnamespace\x18\x05 \x01(\v2#.proto.types.StringFilterExpressionR\tnamespace\x12d\n" +
	"\x1drequire_refresh_client_secret\x18\x06 \x01(\v2!.proto.types.BoolFilterExpressionR\x1arequireRefreshClientSecret\x12S\n" +
	"\x14allow_offline_access\x18\a \x01(\v2!.proto.types.BoolFilterExpressionR\x12allowOfflineAccess\x12r\n" +
	"%update_access_token_claims_on_refresh\x18\b \x01(\v2!.proto.types.BoolFilterExpressionR updateAccessTokenClaimsOnRefresh\x12G\n" +
	"\x0einclude_jwt_id\x18\t \x01(\v2!.proto.types.BoolFilterExpressionR\fincludeJwtId\x12\\\n" +
	"\x19always_send_client_claims\x18\n" +
	" \x01(\v2!.proto.types.BoolFilterExpressionR\x16alwaysSendClientClaims\x12s\n" +
	"&always_include_user_claims_in_id_token\x18\v \x01(\v2!.proto.types.BoolFilterExpressionR alwaysIncludeUserClaimsInIdToken\x12U\n" +
	"\x15require_client_secret\x18\f \x01(\v2!.proto.types.BoolFilterExpressionR\x13requireClientSecret\x12W\n" +
	"\x15access_token_lifetime\x18\r \x01(\v2#.proto.types.UInt64FilterExpressionR\x13accessTokenLifetime\x12j\n" +
	"\x1fabsolute_refresh_token_lifetime\x18\x0e \x01(\v2#.proto.types.UInt64FilterExpressionR\x1cabsoluteRefreshTokenLifetime\x12h\n" +
	"\x1esliding_refresh_token_lifetime\x18\x0f \x01(\v2#.proto.types.UInt64FilterExpressionR\x1bslidingRefreshTokenLifetime\x12[\n" +
	"\x17identity_token_lifetime\x18\x10 \x01(\v2#.proto.types.UInt64FilterExpressionR\x15identityTokenLifetime\x12`\n" +
	"\x1brefresh_token_grace_enabled\x18\x11 \x01(\v2!.proto.types.BoolFilterExpressionR\x18refreshTokenGraceEnabled\x12Z\n" +
	"\x17refresh_token_grace_ttl\x18\x12 \x01(\v2#.proto.types.UInt64FilterExpressionR\x14refreshTokenGraceTtl\x12k\n" +
	" refresh_token_grace_max_attempts\x18\x13 \x01(\v2#.proto.types.UInt64FilterExpressionR\x1crefreshTokenGraceMaxAttempts\x12S\n" +
	"\x13refresh_token_usage\x18\x14 \x01(\v2#.proto.types.UInt64FilterExpressionR\x11refreshTokenUsage\x12]\n" +
	"\x18refresh_token_expiration\x18\x15 \x01(\v2#.proto.types.UInt64FilterExpressionR\x16refreshTokenExpiration\x12O\n" +
	"\x11access_token_type\x18\x16 \x01(\v2#.proto.types.UInt64FilterExpressionR\x0faccessTokenType\x12O\n" +
	"\x0eallowed_scopes\x18\x18 \x01(\v2(.proto.types.StringArrayFilterExpressionR\rallowedScopes\x12X\n" +
	"\x13allowed_grant_types\x18\x19 \x01(\v2(.proto.types.StringArrayFilterExpressionR\x11allowedGrantTypes\x12Y\n" +
	"\x13allowed_permissions\x18\x1b \x01(\v2(.proto.types.StringArrayFilterExpressionR\x12allowedPermissions\x12g\n" +
	"\x1ballowed_dynamic_claim_types\x18\x1c \x01(\v2(.proto.types.StringArrayFilterExpressionR\x18allowedDynamicClaimTypes\x12\x87\x01\n" +
	",allowed_token_exchange_requested_token_types\x18\x1d \x01(\v2(.proto.types.StringArrayFilterExpressionR'allowedTokenExchangeRequestedTokenTypes\x12+\n" +
	"\x03and\x18d \x03(\v2\x19.proto.oidc.client.FilterR\x03and\x12)\n" +
	"\x02or\x18e \x03(\v2\x19.proto.oidc.client.FilterR\x02or\x12+\n" +
	"\x03not\x18f \x03(\v2\x19.proto.oidc.client.FilterR\x03not\"R\n" +
	"\x1bValidateClientSecretRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"4\n" +
	"\x1cValidateClientSecretResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"\xab\x01\n" +
	"\x19AddNewClientSecretRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fexpiration_unix\x18\x03 \x01(\x03R\x0eexpirationUnix\x124\n" +
	"\x06secret\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x06secret\"\x87\x01\n" +
	"\x1aAddNewClientSecretResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12L\n" +
	"\rclient_secret\x18\x02 \x01(\v2'.proto.oidc.models.ClientSecretResponseR\fclientSecret\"H\n" +
	"\x13CreateClientRequest\x121\n" +
	"\x06client\x18\x01 \x01(\v2\x19.proto.oidc.models.ClientR\x06client\"I\n" +
	"\x14CreateClientResponse\x121\n" +
	"\x06client\x18\x01 \x01(\v2\x19.proto.oidc.models.ClientR\x06client\"/\n" +
	"\x10GetClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"F\n" +
	"\x11GetClientResponse\x121\n" +
	"\x06client\x18\x01 \x01(\v2\x19.proto.oidc.models.ClientR\x06client\"2\n" +
	"\x13DeleteClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x16\n" +
	"\x14DeleteClientResponse\"N\n" +
	"\x13UpdateClientRequest\x127\n" +
	"\x06client\x18\x01 \x01(\v2\x1f.proto.oidc.models.ClientUpdateR\x06client\"I\n" +
	"\x14UpdateClientResponse\x121\n" +
	"\x06client\x18\x01 \x01(\v2\x19.proto.oidc.models.ClientR\x06client\"\x7f\n" +
	"\x11ListClientRequest\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.proto.oidc.client.FilterR\x06filter\x127\n" +
	"\n" +
	"pagination\x18d \x01(\v2\x17.proto.types.PaginationR\n" +
	"pagination\"\x8a\x01\n" +
	"\x12ListClientResponse\x123\n" +
	"\aclients\x18\x01 \x03(\v2\x19.proto.oidc.models.ClientR\aclients\x12?\n" +
	"\n" +
	"pagination\x18d \x01(\v2\x1f.proto.types.PaginationResponseR\n" +
	"pagination2\xc3\a\n" +
	"\rClientService\x12\x82\x01\n" +
	"\fCreateClient\x12&.proto.oidc.client.CreateClientRequest\x1a'.proto.oidc.client.CreateClientResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/Client/_create\x12\x84\x01\n" +
	"\tGetClient\x12#.proto.oidc.client.GetClientRequest\x1a$.proto.oidc.client.GetClientResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/Client/client_id/{client_id}\x12\x8d\x01\n" +
	"\fDeleteClient\x12&.proto.oidc.client.DeleteClientRequest\x1a'.proto.oidc.client.DeleteClientResponse\",\x82\xd3\xe4\x93\x02&*$/api/v1/Client/client_id/{client_id}\x12\x82\x01\n" +
	"\fUpdateClient\x12&.proto.oidc.client.UpdateClientRequest\x1a'.proto.oidc.client.UpdateClientResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/Client/_update\x12|\n" +
	"\n" +
	"ListClient\x12$.proto.oidc.client.ListClientRequest\x1a%.proto.oidc.client.ListClientResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/Client/_search\x12\x97\x01\n" +
	"\x12AddNewClientSecret\x12,.proto.oidc.client.AddNewClientSecretRequest\x1a-.proto.oidc.client.AddNewClientSecretResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/Client/add/secret\x12y\n" +
	"\x14ValidateClientSecret\x12..proto.oidc.client.ValidateClientSecretRequest\x1a/.proto.oidc.client.ValidateClientSecretResponse\"\x00B\x91\x01\n" +
	"\x1fcom.fluffybunny.rageoidc.clientP\x01ZIgithub.com/fluffy-bunny/fluffycore-rage-identity/proto/oidc/client;client\xaa\x02 FluffyBunny.RageOidc.Oidc.Clientb\x06proto3"

var (
	file_proto_oidc_client_client_proto_rawDescOnce sync.Once
	file_proto_oidc_client_client_proto_rawDescData []byte
)

func file_proto_oidc_client_client_proto_rawDescGZIP() []byte {
	file_proto_oidc_client_client_proto_rawDescOnce.Do(func() {
		file_proto_oidc_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oidc_client_client_proto_rawDesc), len(file_proto_oidc_client_client_proto_rawDesc)))
	})
	return file_proto_oidc_client_client_proto_rawDescData
}

var file_proto_oidc_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_oidc_client_client_proto_goTypes = []any{
	(*Filter)(nil),                            // 0: proto.oidc.client.Filter
	(*ValidateClientSecretRequest)(nil),       // 1: proto.oidc.client.ValidateClientSecretRequest
	(*ValidateClientSecretResponse)(nil),      // 2: proto.oidc.client.ValidateClientSecretResponse
	(*AddNewClientSecretRequest)(nil),         // 3: proto.oidc.client.AddNewClientSecretRequest
	(*AddNewClientSecretResponse)(nil),        // 4: proto.oidc.client.AddNewClientSecretResponse
	(*CreateClientRequest)(nil),               // 5: proto.oidc.client.CreateClientRequest
	(*CreateClientResponse)(nil),              // 6: proto.oidc.client.CreateClientResponse
	(*GetClientRequest)(nil),                  // 7: proto.oidc.client.GetClientRequest
	(*GetClientResponse)(nil),                 // 8: proto.oidc.client.GetClientResponse
	(*DeleteClientRequest)(nil),               // 9: proto.oidc.client.DeleteClientRequest
	(*DeleteClientResponse)(nil),              // 10: proto.oidc.client.DeleteClientResponse
	(*UpdateClientRequest)(nil),               // 11: proto.oidc.client.UpdateClientRequest
	(*UpdateClientResponse)(nil),              // 12: proto.oidc.client.UpdateClientResponse
	(*ListClientRequest)(nil),                 // 13: proto.oidc.client.ListClientRequest
	(*ListClientResponse)(nil),                // 14: proto.oidc.client.ListClientResponse
	(*types.IDFilterExpression)(nil),          // 15: proto.types.IDFilterExpression
	(*types.BoolFilterExpression)(nil),        // 16: proto.types.BoolFilterExpression
	(*types.StringFilterExpression)(nil),      // 17: proto.types.StringFilterExpression
	(*types.UInt64FilterExpression)(nil),      // 18: proto.types.UInt64FilterExpression
	(*types.StringArrayFilterExpression)(nil), // 19: proto.types.StringArrayFilterExpression
	(*wrapperspb.StringValue)(nil),            // 20: google.protobuf.StringValue
	(*models.ClientSecretResponse)(nil),       // 21: proto.oidc.models.ClientSecretResponse
	(*models.Client)(nil),                     // 22: proto.oidc.models.Client
	(*models.ClientUpdate)(nil),               // 23: proto.oidc.models.ClientUpdate
	(*types.Pagination)(nil),                  // 24: proto.types.Pagination
	(*types.PaginationResponse)(nil),          // 25: proto.types.PaginationResponse
}
var file_proto_oidc_client_client_proto_depIdxs = []int32{
	15, // 0: proto.oidc.client.Filter.client_id:type_name -> proto.types.IDFilterExpression
	16, // 1: proto.oidc.client.Filter.enabled:type_name -> proto.types.BoolFilterExpression
	17, // 2: proto.oidc.client.Filter.client_name:type_name -> proto.types.StringFilterExpression
	17, // 3: proto.oidc.client.Filter.description:type_name -> proto.types.StringFilterExpression
	17, // 4: proto.oidc.client.Filter.namespace:type_name -> proto.types.StringFilterExpression
	16, // 5: proto.oidc.client.Filter.require_refresh_client_secret:type_name -> proto.types.BoolFilterExpression
	16, // 6: proto.oidc.client.Filter.allow_offline_access:type_name -> proto.types.BoolFilterExpression
	16, // 7: proto.oidc.client.Filter.update_access_token_claims_on_refresh:type_name -> proto.types.BoolFilterExpression
	16, // 8: proto.oidc.client.Filter.include_jwt_id:type_name -> proto.types.BoolFilterExpression
	16, // 9: proto.oidc.client.Filter.always_send_client_claims:type_name -> proto.types.BoolFilterExpression
	16, // 10: proto.oidc.client.Filter.always_include_user_claims_in_id_token:type_name -> proto.types.BoolFilterExpression
	16, // 11: proto.oidc.client.Filter.require_client_secret:type_name -> proto.types.BoolFilterExpression
	18, // 12: proto.oidc.client.Filter.access_token_lifetime:type_name -> proto.types.UInt64FilterExpression
	18, // 13: proto.oidc.client.Filter.absolute_refresh_token_lifetime:type_name -> proto.types.UInt64FilterExpression
	18, // 14: proto.oidc.client.Filter.sliding_refresh_token_lifetime:type_name -> proto.types.UInt64FilterExpression
	18, // 15: proto.oidc.client.Filter.identity_token_lifetime:type_name -> proto.types.UInt64FilterExpression
	16, // 16: proto.oidc.client.Filter.refresh_token_grace_enabled:type_name -> proto.types.BoolFilterExpression
	18, // 17: proto.oidc.client.Filter.refresh_token_grace_ttl:type_name -> proto.types.UInt64FilterExpression
	18, // 18: proto.oidc.client.Filter.refresh_token_grace_max_attempts:type_name -> proto.types.UInt64FilterExpression
	18, // 19: proto.oidc.client.Filter.refresh_token_usage:type_name -> proto.types.UInt64FilterExpression
	18, // 20: proto.oidc.client.Filter.refresh_token_expiration:type_name -> proto.types.UInt64FilterExpression
	18, // 21: proto.oidc.client.Filter.access_token_type:type_name -> proto.types.UInt64FilterExpression
	19, // 22: proto.oidc.client.Filter.allowed_scopes:type_name -> proto.types.StringArrayFilterExpression
	19, // 23: proto.oidc.client.Filter.allowed_grant_types:type_name -> proto.types.StringArrayFilterExpression
	19, // 24: proto.oidc.client.Filter.allowed_permissions:type_name -> proto.types.StringArrayFilterExpression
	19, // 25: proto.oidc.client.Filter.allowed_dynamic_claim_types:type_name -> proto.types.StringArrayFilterExpression
	19, // 26: proto.oidc.client.Filter.allowed_token_exchange_requested_token_types:type_name -> proto.types.StringArrayFilterExpression
	0,  // 27: proto.oidc.client.Filter.and:type_name -> proto.oidc.client.Filter
	0,  // 28: proto.oidc.client.Filter.or:type_name -> proto.oidc.client.Filter
	0,  // 29: proto.oidc.client.Filter.not:type_name -> proto.oidc.client.Filter
	20, // 30: proto.oidc.client.AddNewClientSecretRequest.secret:type_name -> google.protobuf.StringValue
	21, // 31: proto.oidc.client.AddNewClientSecretResponse.client_secret:type_name -> proto.oidc.models.ClientSecretResponse
	22, // 32: proto.oidc.client.CreateClientRequest.client:type_name -> proto.oidc.models.Client
	22, // 33: proto.oidc.client.CreateClientResponse.client:type_name -> proto.oidc.models.Client
	22, // 34: proto.oidc.client.GetClientResponse.client:type_name -> proto.oidc.models.Client
	23, // 35: proto.oidc.client.UpdateClientRequest.client:type_name -> proto.oidc.models.ClientUpdate
	22, // 36: proto.oidc.client.UpdateClientResponse.client:type_name -> proto.oidc.models.Client
	0,  // 37: proto.oidc.client.ListClientRequest.filter:type_name -> proto.oidc.client.Filter
	24, // 38: proto.oidc.client.ListClientRequest.pagination:type_name -> proto.types.Pagination
	22, // 39: proto.oidc.client.ListClientResponse.clients:type_name -> proto.oidc.models.Client
	25, // 40: proto.oidc.client.ListClientResponse.pagination:type_name -> proto.types.PaginationResponse
	5,  // 41: proto.oidc.client.ClientService.CreateClient:input_type -> proto.oidc.client.CreateClientRequest
	7,  // 42: proto.oidc.client.ClientService.GetClient:input_type -> proto.oidc.client.GetClientRequest
	9,  // 43: proto.oidc.client.ClientService.DeleteClient:input_type -> proto.oidc.client.DeleteClientRequest
	11, // 44: proto.oidc.client.ClientService.UpdateClient:input_type -> proto.oidc.client.UpdateClientRequest
	13, // 45: proto.oidc.client.ClientService.ListClient:input_type -> proto.oidc.client.ListClientRequest
	3,  // 46: proto.oidc.client.ClientService.AddNewClientSecret:input_type -> proto.oidc.client.AddNewClientSecretRequest
	1,  // 47: proto.oidc.client.ClientService.ValidateClientSecret:input_type -> proto.oidc.client.ValidateClientSecretRequest
	6,  // 48: proto.oidc.client.ClientService.CreateClient:output_type -> proto.oidc.client.CreateClientResponse
	8,  // 49: proto.oidc.client.ClientService.GetClient:output_type -> proto.oidc.client.GetClientResponse
	10, // 50: proto.oidc.client.ClientService.DeleteClient:output_type -> proto.oidc.client.DeleteClientResponse
	12, // 51: proto.oidc.client.ClientService.UpdateClient:output_type -> proto.oidc.client.UpdateClientResponse
	14, // 52: proto.oidc.client.ClientService.ListClient:output_type -> proto.oidc.client.ListClientResponse
	4,  // 53: proto.oidc.client.ClientService.AddNewClientSecret:output_type -> proto.oidc.client.AddNewClientSecretResponse
	2,  // 54: proto.oidc.client.ClientService.ValidateClientSecret:output_type -> proto.oidc.client.ValidateClientSecretResponse
	48, // [48:55] is the sub-list for method output_type
	41, // [41:48] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_proto_oidc_client_client_proto_init() }
func file_proto_oidc_client_client_proto_init() {
	if File_proto_oidc_client_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oidc_client_client_proto_rawDesc), len(file_proto_oidc_client_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_oidc_client_client_proto_goTypes,
		DependencyIndexes: file_proto_oidc_client_client_proto_depIdxs,
		MessageInfos:      file_proto_oidc_client_client_proto_msgTypes,
	}.Build()
	File_proto_oidc_client_client_proto = out.File
	file_proto_oidc_client_client_proto_goTypes = nil
	file_proto_oidc_client_client_proto_depIdxs = nil
}
