// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/oidc/flows/oidc_flow.proto

package flows

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OIDCFlowStore_StoreAuthorizationFinal_FullMethodName  = "/proto.oidc.flows.OIDCFlowStore/StoreAuthorizationFinal"
	OIDCFlowStore_GetAuthorizationFinal_FullMethodName    = "/proto.oidc.flows.OIDCFlowStore/GetAuthorizationFinal"
	OIDCFlowStore_DeleteAuthorizationFinal_FullMethodName = "/proto.oidc.flows.OIDCFlowStore/DeleteAuthorizationFinal"
)

// OIDCFlowStoreClient is the client API for OIDCFlowStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OIDCFlowStoreClient interface {
	// Create user
	StoreAuthorizationFinal(ctx context.Context, in *StoreAuthorizationFinalRequest, opts ...grpc.CallOption) (*StoreAuthorizationFinalResponse, error)
	GetAuthorizationFinal(ctx context.Context, in *GetAuthorizationFinalRequest, opts ...grpc.CallOption) (*GetAuthorizationFinalResponse, error)
	DeleteAuthorizationFinal(ctx context.Context, in *DeleteAuthorizationFinalRequest, opts ...grpc.CallOption) (*DeleteAuthorizationFinalResponse, error)
}

type oIDCFlowStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewOIDCFlowStoreClient(cc grpc.ClientConnInterface) OIDCFlowStoreClient {
	return &oIDCFlowStoreClient{cc}
}

func (c *oIDCFlowStoreClient) StoreAuthorizationFinal(ctx context.Context, in *StoreAuthorizationFinalRequest, opts ...grpc.CallOption) (*StoreAuthorizationFinalResponse, error) {
	out := new(StoreAuthorizationFinalResponse)
	err := c.cc.Invoke(ctx, OIDCFlowStore_StoreAuthorizationFinal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oIDCFlowStoreClient) GetAuthorizationFinal(ctx context.Context, in *GetAuthorizationFinalRequest, opts ...grpc.CallOption) (*GetAuthorizationFinalResponse, error) {
	out := new(GetAuthorizationFinalResponse)
	err := c.cc.Invoke(ctx, OIDCFlowStore_GetAuthorizationFinal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oIDCFlowStoreClient) DeleteAuthorizationFinal(ctx context.Context, in *DeleteAuthorizationFinalRequest, opts ...grpc.CallOption) (*DeleteAuthorizationFinalResponse, error) {
	out := new(DeleteAuthorizationFinalResponse)
	err := c.cc.Invoke(ctx, OIDCFlowStore_DeleteAuthorizationFinal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OIDCFlowStoreServer is the server API for OIDCFlowStore service.
// All implementations must embed UnimplementedOIDCFlowStoreServer
// for forward compatibility
type OIDCFlowStoreServer interface {
	// Create user
	StoreAuthorizationFinal(context.Context, *StoreAuthorizationFinalRequest) (*StoreAuthorizationFinalResponse, error)
	GetAuthorizationFinal(context.Context, *GetAuthorizationFinalRequest) (*GetAuthorizationFinalResponse, error)
	DeleteAuthorizationFinal(context.Context, *DeleteAuthorizationFinalRequest) (*DeleteAuthorizationFinalResponse, error)
	mustEmbedUnimplementedOIDCFlowStoreServer()
}

// UnimplementedOIDCFlowStoreServer must be embedded to have forward compatible implementations.
type UnimplementedOIDCFlowStoreServer struct {
}

func (UnimplementedOIDCFlowStoreServer) StoreAuthorizationFinal(context.Context, *StoreAuthorizationFinalRequest) (*StoreAuthorizationFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreAuthorizationFinal not implemented")
}
func (UnimplementedOIDCFlowStoreServer) GetAuthorizationFinal(context.Context, *GetAuthorizationFinalRequest) (*GetAuthorizationFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorizationFinal not implemented")
}
func (UnimplementedOIDCFlowStoreServer) DeleteAuthorizationFinal(context.Context, *DeleteAuthorizationFinalRequest) (*DeleteAuthorizationFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAuthorizationFinal not implemented")
}
func (UnimplementedOIDCFlowStoreServer) mustEmbedUnimplementedOIDCFlowStoreServer() {}

// UnsafeOIDCFlowStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OIDCFlowStoreServer will
// result in compilation errors.
type UnsafeOIDCFlowStoreServer interface {
	mustEmbedUnimplementedOIDCFlowStoreServer()
}

func RegisterOIDCFlowStoreServer(s grpc.ServiceRegistrar, srv OIDCFlowStoreServer) {
	s.RegisterService(&OIDCFlowStore_ServiceDesc, srv)
}

func _OIDCFlowStore_StoreAuthorizationFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreAuthorizationFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCFlowStoreServer).StoreAuthorizationFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCFlowStore_StoreAuthorizationFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCFlowStoreServer).StoreAuthorizationFinal(ctx, req.(*StoreAuthorizationFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OIDCFlowStore_GetAuthorizationFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCFlowStoreServer).GetAuthorizationFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCFlowStore_GetAuthorizationFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCFlowStoreServer).GetAuthorizationFinal(ctx, req.(*GetAuthorizationFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OIDCFlowStore_DeleteAuthorizationFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthorizationFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCFlowStoreServer).DeleteAuthorizationFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCFlowStore_DeleteAuthorizationFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCFlowStoreServer).DeleteAuthorizationFinal(ctx, req.(*DeleteAuthorizationFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OIDCFlowStore_ServiceDesc is the grpc.ServiceDesc for OIDCFlowStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OIDCFlowStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.oidc.flows.OIDCFlowStore",
	HandlerType: (*OIDCFlowStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreAuthorizationFinal",
			Handler:    _OIDCFlowStore_StoreAuthorizationFinal_Handler,
		},
		{
			MethodName: "GetAuthorizationFinal",
			Handler:    _OIDCFlowStore_GetAuthorizationFinal_Handler,
		},
		{
			MethodName: "DeleteAuthorizationFinal",
			Handler:    _OIDCFlowStore_DeleteAuthorizationFinal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oidc/flows/oidc_flow.proto",
}

const (
	ExternalOauth2FlowStore_StoreExternalOauth2Final_FullMethodName  = "/proto.oidc.flows.ExternalOauth2FlowStore/StoreExternalOauth2Final"
	ExternalOauth2FlowStore_GetExternalOauth2Final_FullMethodName    = "/proto.oidc.flows.ExternalOauth2FlowStore/GetExternalOauth2Final"
	ExternalOauth2FlowStore_DeleteExternalOauth2Final_FullMethodName = "/proto.oidc.flows.ExternalOauth2FlowStore/DeleteExternalOauth2Final"
)

// ExternalOauth2FlowStoreClient is the client API for ExternalOauth2FlowStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalOauth2FlowStoreClient interface {
	// Create user
	StoreExternalOauth2Final(ctx context.Context, in *StoreExternalOauth2FinalRequest, opts ...grpc.CallOption) (*StoreExternalOauth2FinalResponse, error)
	GetExternalOauth2Final(ctx context.Context, in *GetExternalOauth2FinalRequest, opts ...grpc.CallOption) (*GetExternalOauth2FinalResponse, error)
	DeleteExternalOauth2Final(ctx context.Context, in *DeleteExternalOauth2FinalRequest, opts ...grpc.CallOption) (*DeleteExternalOauth2FinalResponse, error)
}

type externalOauth2FlowStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalOauth2FlowStoreClient(cc grpc.ClientConnInterface) ExternalOauth2FlowStoreClient {
	return &externalOauth2FlowStoreClient{cc}
}

func (c *externalOauth2FlowStoreClient) StoreExternalOauth2Final(ctx context.Context, in *StoreExternalOauth2FinalRequest, opts ...grpc.CallOption) (*StoreExternalOauth2FinalResponse, error) {
	out := new(StoreExternalOauth2FinalResponse)
	err := c.cc.Invoke(ctx, ExternalOauth2FlowStore_StoreExternalOauth2Final_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalOauth2FlowStoreClient) GetExternalOauth2Final(ctx context.Context, in *GetExternalOauth2FinalRequest, opts ...grpc.CallOption) (*GetExternalOauth2FinalResponse, error) {
	out := new(GetExternalOauth2FinalResponse)
	err := c.cc.Invoke(ctx, ExternalOauth2FlowStore_GetExternalOauth2Final_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalOauth2FlowStoreClient) DeleteExternalOauth2Final(ctx context.Context, in *DeleteExternalOauth2FinalRequest, opts ...grpc.CallOption) (*DeleteExternalOauth2FinalResponse, error) {
	out := new(DeleteExternalOauth2FinalResponse)
	err := c.cc.Invoke(ctx, ExternalOauth2FlowStore_DeleteExternalOauth2Final_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalOauth2FlowStoreServer is the server API for ExternalOauth2FlowStore service.
// All implementations must embed UnimplementedExternalOauth2FlowStoreServer
// for forward compatibility
type ExternalOauth2FlowStoreServer interface {
	// Create user
	StoreExternalOauth2Final(context.Context, *StoreExternalOauth2FinalRequest) (*StoreExternalOauth2FinalResponse, error)
	GetExternalOauth2Final(context.Context, *GetExternalOauth2FinalRequest) (*GetExternalOauth2FinalResponse, error)
	DeleteExternalOauth2Final(context.Context, *DeleteExternalOauth2FinalRequest) (*DeleteExternalOauth2FinalResponse, error)
	mustEmbedUnimplementedExternalOauth2FlowStoreServer()
}

// UnimplementedExternalOauth2FlowStoreServer must be embedded to have forward compatible implementations.
type UnimplementedExternalOauth2FlowStoreServer struct {
}

func (UnimplementedExternalOauth2FlowStoreServer) StoreExternalOauth2Final(context.Context, *StoreExternalOauth2FinalRequest) (*StoreExternalOauth2FinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreExternalOauth2Final not implemented")
}
func (UnimplementedExternalOauth2FlowStoreServer) GetExternalOauth2Final(context.Context, *GetExternalOauth2FinalRequest) (*GetExternalOauth2FinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExternalOauth2Final not implemented")
}
func (UnimplementedExternalOauth2FlowStoreServer) DeleteExternalOauth2Final(context.Context, *DeleteExternalOauth2FinalRequest) (*DeleteExternalOauth2FinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExternalOauth2Final not implemented")
}
func (UnimplementedExternalOauth2FlowStoreServer) mustEmbedUnimplementedExternalOauth2FlowStoreServer() {
}

// UnsafeExternalOauth2FlowStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalOauth2FlowStoreServer will
// result in compilation errors.
type UnsafeExternalOauth2FlowStoreServer interface {
	mustEmbedUnimplementedExternalOauth2FlowStoreServer()
}

func RegisterExternalOauth2FlowStoreServer(s grpc.ServiceRegistrar, srv ExternalOauth2FlowStoreServer) {
	s.RegisterService(&ExternalOauth2FlowStore_ServiceDesc, srv)
}

func _ExternalOauth2FlowStore_StoreExternalOauth2Final_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreExternalOauth2FinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalOauth2FlowStoreServer).StoreExternalOauth2Final(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalOauth2FlowStore_StoreExternalOauth2Final_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalOauth2FlowStoreServer).StoreExternalOauth2Final(ctx, req.(*StoreExternalOauth2FinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalOauth2FlowStore_GetExternalOauth2Final_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExternalOauth2FinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalOauth2FlowStoreServer).GetExternalOauth2Final(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalOauth2FlowStore_GetExternalOauth2Final_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalOauth2FlowStoreServer).GetExternalOauth2Final(ctx, req.(*GetExternalOauth2FinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalOauth2FlowStore_DeleteExternalOauth2Final_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExternalOauth2FinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalOauth2FlowStoreServer).DeleteExternalOauth2Final(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalOauth2FlowStore_DeleteExternalOauth2Final_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalOauth2FlowStoreServer).DeleteExternalOauth2Final(ctx, req.(*DeleteExternalOauth2FinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalOauth2FlowStore_ServiceDesc is the grpc.ServiceDesc for ExternalOauth2FlowStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalOauth2FlowStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.oidc.flows.ExternalOauth2FlowStore",
	HandlerType: (*ExternalOauth2FlowStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreExternalOauth2Final",
			Handler:    _ExternalOauth2FlowStore_StoreExternalOauth2Final_Handler,
		},
		{
			MethodName: "GetExternalOauth2Final",
			Handler:    _ExternalOauth2FlowStore_GetExternalOauth2Final_Handler,
		},
		{
			MethodName: "DeleteExternalOauth2Final",
			Handler:    _ExternalOauth2FlowStore_DeleteExternalOauth2Final_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oidc/flows/oidc_flow.proto",
}
