// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/oidc/flows/oidc_flow.proto

package flows

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthorizationRequestStateStore_StoreAuthorizationRequestState_FullMethodName  = "/proto.oidc.flows.AuthorizationRequestStateStore/StoreAuthorizationRequestState"
	AuthorizationRequestStateStore_GetAuthorizationRequestState_FullMethodName    = "/proto.oidc.flows.AuthorizationRequestStateStore/GetAuthorizationRequestState"
	AuthorizationRequestStateStore_DeleteAuthorizationRequestState_FullMethodName = "/proto.oidc.flows.AuthorizationRequestStateStore/DeleteAuthorizationRequestState"
)

// AuthorizationRequestStateStoreClient is the client API for AuthorizationRequestStateStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizationRequestStateStoreClient interface {
	// Create user
	StoreAuthorizationRequestState(ctx context.Context, in *StoreAuthorizationRequestStateRequest, opts ...grpc.CallOption) (*StoreAuthorizationRequestStateResponse, error)
	GetAuthorizationRequestState(ctx context.Context, in *GetAuthorizationRequestStateRequest, opts ...grpc.CallOption) (*GetAuthorizationRequestStateResponse, error)
	DeleteAuthorizationRequestState(ctx context.Context, in *DeleteAuthorizationRequestStateRequest, opts ...grpc.CallOption) (*DeleteAuthorizationRequestStateResponse, error)
}

type authorizationRequestStateStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationRequestStateStoreClient(cc grpc.ClientConnInterface) AuthorizationRequestStateStoreClient {
	return &authorizationRequestStateStoreClient{cc}
}

func (c *authorizationRequestStateStoreClient) StoreAuthorizationRequestState(ctx context.Context, in *StoreAuthorizationRequestStateRequest, opts ...grpc.CallOption) (*StoreAuthorizationRequestStateResponse, error) {
	out := new(StoreAuthorizationRequestStateResponse)
	err := c.cc.Invoke(ctx, AuthorizationRequestStateStore_StoreAuthorizationRequestState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationRequestStateStoreClient) GetAuthorizationRequestState(ctx context.Context, in *GetAuthorizationRequestStateRequest, opts ...grpc.CallOption) (*GetAuthorizationRequestStateResponse, error) {
	out := new(GetAuthorizationRequestStateResponse)
	err := c.cc.Invoke(ctx, AuthorizationRequestStateStore_GetAuthorizationRequestState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationRequestStateStoreClient) DeleteAuthorizationRequestState(ctx context.Context, in *DeleteAuthorizationRequestStateRequest, opts ...grpc.CallOption) (*DeleteAuthorizationRequestStateResponse, error) {
	out := new(DeleteAuthorizationRequestStateResponse)
	err := c.cc.Invoke(ctx, AuthorizationRequestStateStore_DeleteAuthorizationRequestState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationRequestStateStoreServer is the server API for AuthorizationRequestStateStore service.
// All implementations must embed UnimplementedAuthorizationRequestStateStoreServer
// for forward compatibility
type AuthorizationRequestStateStoreServer interface {
	// Create user
	StoreAuthorizationRequestState(context.Context, *StoreAuthorizationRequestStateRequest) (*StoreAuthorizationRequestStateResponse, error)
	GetAuthorizationRequestState(context.Context, *GetAuthorizationRequestStateRequest) (*GetAuthorizationRequestStateResponse, error)
	DeleteAuthorizationRequestState(context.Context, *DeleteAuthorizationRequestStateRequest) (*DeleteAuthorizationRequestStateResponse, error)
	mustEmbedUnimplementedAuthorizationRequestStateStoreServer()
}

// UnimplementedAuthorizationRequestStateStoreServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizationRequestStateStoreServer struct {
}

func (UnimplementedAuthorizationRequestStateStoreServer) StoreAuthorizationRequestState(context.Context, *StoreAuthorizationRequestStateRequest) (*StoreAuthorizationRequestStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreAuthorizationRequestState not implemented")
}
func (UnimplementedAuthorizationRequestStateStoreServer) GetAuthorizationRequestState(context.Context, *GetAuthorizationRequestStateRequest) (*GetAuthorizationRequestStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorizationRequestState not implemented")
}
func (UnimplementedAuthorizationRequestStateStoreServer) DeleteAuthorizationRequestState(context.Context, *DeleteAuthorizationRequestStateRequest) (*DeleteAuthorizationRequestStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAuthorizationRequestState not implemented")
}
func (UnimplementedAuthorizationRequestStateStoreServer) mustEmbedUnimplementedAuthorizationRequestStateStoreServer() {
}

// UnsafeAuthorizationRequestStateStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationRequestStateStoreServer will
// result in compilation errors.
type UnsafeAuthorizationRequestStateStoreServer interface {
	mustEmbedUnimplementedAuthorizationRequestStateStoreServer()
}

func RegisterAuthorizationRequestStateStoreServer(s grpc.ServiceRegistrar, srv AuthorizationRequestStateStoreServer) {
	s.RegisterService(&AuthorizationRequestStateStore_ServiceDesc, srv)
}

func _AuthorizationRequestStateStore_StoreAuthorizationRequestState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreAuthorizationRequestStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationRequestStateStoreServer).StoreAuthorizationRequestState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationRequestStateStore_StoreAuthorizationRequestState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationRequestStateStoreServer).StoreAuthorizationRequestState(ctx, req.(*StoreAuthorizationRequestStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationRequestStateStore_GetAuthorizationRequestState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationRequestStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationRequestStateStoreServer).GetAuthorizationRequestState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationRequestStateStore_GetAuthorizationRequestState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationRequestStateStoreServer).GetAuthorizationRequestState(ctx, req.(*GetAuthorizationRequestStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationRequestStateStore_DeleteAuthorizationRequestState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthorizationRequestStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationRequestStateStoreServer).DeleteAuthorizationRequestState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationRequestStateStore_DeleteAuthorizationRequestState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationRequestStateStoreServer).DeleteAuthorizationRequestState(ctx, req.(*DeleteAuthorizationRequestStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizationRequestStateStore_ServiceDesc is the grpc.ServiceDesc for AuthorizationRequestStateStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationRequestStateStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.oidc.flows.AuthorizationRequestStateStore",
	HandlerType: (*AuthorizationRequestStateStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreAuthorizationRequestState",
			Handler:    _AuthorizationRequestStateStore_StoreAuthorizationRequestState_Handler,
		},
		{
			MethodName: "GetAuthorizationRequestState",
			Handler:    _AuthorizationRequestStateStore_GetAuthorizationRequestState_Handler,
		},
		{
			MethodName: "DeleteAuthorizationRequestState",
			Handler:    _AuthorizationRequestStateStore_DeleteAuthorizationRequestState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oidc/flows/oidc_flow.proto",
}
