// Code generated by protoc-gen-go-fluffycore-di. DO NOT EDIT.
// Code generated grpcGateway

package flows

import (
	context "context"
	fluffy_dozm_di "github.com/fluffy-bunny/fluffy-dozm-di"
	GRPCClientFactory "github.com/fluffy-bunny/fluffycore/contracts/GRPCClientFactory"
	endpoint "github.com/fluffy-bunny/fluffycore/contracts/endpoint"
	tokensource "github.com/fluffy-bunny/fluffycore/contracts/tokensource"
	grpcclient "github.com/fluffy-bunny/fluffycore/grpcclient"
	dicontext "github.com/fluffy-bunny/fluffycore/middleware/dicontext"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
	sync "sync"
)

// IAppAuthorizationRequestStateStoreClientAccessor defines the grpc client
type IAppAuthorizationRequestStateStoreClientAccessor interface {
	GetClient() (AuthorizationRequestStateStoreClient, error)
}

// AppAuthorizationRequestStateStoreClientAccessorConfig defines the grpc client struct
type AppAuthorizationRequestStateStoreClientAccessorConfig struct {
	Url string
}

// AppAuthorizationRequestStateStoreClientAccessor defines the grpc client struct
type AppAuthorizationRequestStateStoreClientAccessor struct {
	rwLock            sync.RWMutex
	config            *AppAuthorizationRequestStateStoreClientAccessorConfig
	appTokenSource    tokensource.IAppTokenSource
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory
	client            AuthorizationRequestStateStoreClient
}

var stemAppAuthorizationRequestStateStoreClientAccessor = (*AppAuthorizationRequestStateStoreClientAccessor)(nil)
var _ IAppAuthorizationRequestStateStoreClientAccessor = stemAppAuthorizationRequestStateStoreClientAccessor

func (s *AppAuthorizationRequestStateStoreClientAccessor) Ctor(
	config *AppAuthorizationRequestStateStoreClientAccessorConfig,
	appTokenSource tokensource.IAppTokenSource,
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory,
) (IAppAuthorizationRequestStateStoreClientAccessor, error) {
	return &AppAuthorizationRequestStateStoreClientAccessor{
		config:            config,
		appTokenSource:    appTokenSource,
		grpcClientFactory: grpcClientFactory,
	}, nil
}

// AddSingletonIAppAuthorizationRequestStateStoreClientAccessor ...
func AddSingletonIAppAuthorizationRequestStateStoreClientAccessor(
	cb fluffy_dozm_di.ContainerBuilder,
	config *AppAuthorizationRequestStateStoreClientAccessorConfig,
) {
	fluffy_dozm_di.AddInstance[*AppAuthorizationRequestStateStoreClientAccessorConfig](cb, config)
	fluffy_dozm_di.AddSingleton[IAppAuthorizationRequestStateStoreClientAccessor](cb, stemAppAuthorizationRequestStateStoreClientAccessor.Ctor)
}

func (s *AppAuthorizationRequestStateStoreClientAccessor) GetClient() (AuthorizationRequestStateStoreClient, error) {
	doGetClient := func() AuthorizationRequestStateStoreClient {
		s.rwLock.RLock()
		defer s.rwLock.RUnlock()
		if s.client != nil {
			return s.client
		}
		return nil
	}

	client := doGetClient()
	if client != nil {
		return client, nil
	}

	tokenSource, err := s.appTokenSource.GetTokenSource()
	if err != nil {
		return nil, err
	}
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--
	s.rwLock.Lock()
	defer s.rwLock.Unlock()
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--

	grpcClient, err := s.grpcClientFactory.NewGrpcClient(
		grpcclient.WithTarget(s.config.Url),
		grpcclient.WithTokenSource(tokenSource),
		grpcclient.WithInsecure(true), // TODO: remove this in production
	)
	if err != nil {
		return nil, err
	}
	s.client = NewAuthorizationRequestStateStoreClient(grpcClient.GetConnection())
	return s.client, nil
}

// IFluffyCoreAuthorizationRequestStateStoreServer defines the grpc server
type IFluffyCoreAuthorizationRequestStateStoreServer interface {
	AuthorizationRequestStateStoreServer
}

type UnimplementedFluffyCoreAuthorizationRequestStateStoreServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreAuthorizationRequestStateStoreServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// AuthorizationRequestStateStoreFluffyCoreServer defines the grpc server truct
type AuthorizationRequestStateStoreFluffyCoreServer struct {
	UnimplementedAuthorizationRequestStateStoreServer
	UnimplementedFluffyCoreAuthorizationRequestStateStoreServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *AuthorizationRequestStateStoreFluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterAuthorizationRequestStateStoreServer(s, srv)
}

// AddAuthorizationRequestStateStoreServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddAuthorizationRequestStateStoreServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreAuthorizationRequestStateStoreServer](cb, ctor)
}

// AddAuthorizationRequestStateStoreServer adds the fluffycore aware grpc server
func AddAuthorizationRequestStateStoreServer(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddAuthorizationRequestStateStoreServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &AuthorizationRequestStateStoreFluffyCoreServer{}
	})
}

// StoreAuthorizationRequestState...
func (s *AuthorizationRequestStateStoreFluffyCoreServer) StoreAuthorizationRequestState(ctx context.Context, request *StoreAuthorizationRequestStateRequest) (*StoreAuthorizationRequestStateResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreAuthorizationRequestStateStoreServer](requestContainer)
	return downstreamService.StoreAuthorizationRequestState(ctx, request)
}

// GetAuthorizationRequestState...
func (s *AuthorizationRequestStateStoreFluffyCoreServer) GetAuthorizationRequestState(ctx context.Context, request *GetAuthorizationRequestStateRequest) (*GetAuthorizationRequestStateResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreAuthorizationRequestStateStoreServer](requestContainer)
	return downstreamService.GetAuthorizationRequestState(ctx, request)
}

// DeleteAuthorizationRequestState...
func (s *AuthorizationRequestStateStoreFluffyCoreServer) DeleteAuthorizationRequestState(ctx context.Context, request *DeleteAuthorizationRequestStateRequest) (*DeleteAuthorizationRequestStateResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreAuthorizationRequestStateStoreServer](requestContainer)
	return downstreamService.DeleteAuthorizationRequestState(ctx, request)
}
