// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/oidc/flows/oidc_flow.proto

package flows

import (
	models "github.com/fluffy-bunny/fluffycore-rage-identity/proto/oidc/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreAuthorizationRequestStateRequest struct {
	state                     protoimpl.MessageState            `protogen:"open.v1"`
	State                     string                            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	AuthorizationRequestState *models.AuthorizationRequestState `protobuf:"bytes,2,opt,name=authorization_request_state,json=authorizationRequestState,proto3" json:"authorization_request_state,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StoreAuthorizationRequestStateRequest) Reset() {
	*x = StoreAuthorizationRequestStateRequest{}
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAuthorizationRequestStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAuthorizationRequestStateRequest) ProtoMessage() {}

func (x *StoreAuthorizationRequestStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreAuthorizationRequestStateRequest.ProtoReflect.Descriptor instead.
func (*StoreAuthorizationRequestStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_flows_oidc_flow_proto_rawDescGZIP(), []int{0}
}

func (x *StoreAuthorizationRequestStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StoreAuthorizationRequestStateRequest) GetAuthorizationRequestState() *models.AuthorizationRequestState {
	if x != nil {
		return x.AuthorizationRequestState
	}
	return nil
}

type StoreAuthorizationRequestStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreAuthorizationRequestStateResponse) Reset() {
	*x = StoreAuthorizationRequestStateResponse{}
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAuthorizationRequestStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAuthorizationRequestStateResponse) ProtoMessage() {}

func (x *StoreAuthorizationRequestStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreAuthorizationRequestStateResponse.ProtoReflect.Descriptor instead.
func (*StoreAuthorizationRequestStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_flows_oidc_flow_proto_rawDescGZIP(), []int{1}
}

type GetAuthorizationRequestStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizationRequestStateRequest) Reset() {
	*x = GetAuthorizationRequestStateRequest{}
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationRequestStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationRequestStateRequest) ProtoMessage() {}

func (x *GetAuthorizationRequestStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationRequestStateRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationRequestStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_flows_oidc_flow_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthorizationRequestStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetAuthorizationRequestStateResponse struct {
	state                     protoimpl.MessageState            `protogen:"open.v1"`
	AuthorizationRequestState *models.AuthorizationRequestState `protobuf:"bytes,1,opt,name=authorization_request_state,json=authorizationRequestState,proto3" json:"authorization_request_state,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetAuthorizationRequestStateResponse) Reset() {
	*x = GetAuthorizationRequestStateResponse{}
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationRequestStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationRequestStateResponse) ProtoMessage() {}

func (x *GetAuthorizationRequestStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationRequestStateResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorizationRequestStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_flows_oidc_flow_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorizationRequestStateResponse) GetAuthorizationRequestState() *models.AuthorizationRequestState {
	if x != nil {
		return x.AuthorizationRequestState
	}
	return nil
}

type DeleteAuthorizationRequestStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthorizationRequestStateRequest) Reset() {
	*x = DeleteAuthorizationRequestStateRequest{}
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthorizationRequestStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorizationRequestStateRequest) ProtoMessage() {}

func (x *DeleteAuthorizationRequestStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorizationRequestStateRequest.ProtoReflect.Descriptor instead.
func (*DeleteAuthorizationRequestStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_oidc_flows_oidc_flow_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAuthorizationRequestStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type DeleteAuthorizationRequestStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthorizationRequestStateResponse) Reset() {
	*x = DeleteAuthorizationRequestStateResponse{}
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthorizationRequestStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorizationRequestStateResponse) ProtoMessage() {}

func (x *DeleteAuthorizationRequestStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oidc_flows_oidc_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorizationRequestStateResponse.ProtoReflect.Descriptor instead.
func (*DeleteAuthorizationRequestStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_oidc_flows_oidc_flow_proto_rawDescGZIP(), []int{5}
}

var File_proto_oidc_flows_oidc_flow_proto protoreflect.FileDescriptor

const file_proto_oidc_flows_oidc_flow_proto_rawDesc = "" +
	"\n" +
	" proto/oidc/flows/oidc_flow.proto\x12\x10proto.oidc.flows\x1a google/protobuf/descriptor.proto\x1a\x1cproto/oidc/models/user.proto\"\xab\x01\n" +
	"%StoreAuthorizationRequestStateRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12l\n" +
	"\x1bauthorization_request_state\x18\x02 \x01(\v2,.proto.oidc.models.AuthorizationRequestStateR\x19authorizationRequestState\"(\n" +
	"&StoreAuthorizationRequestStateResponse\";\n" +
	"#GetAuthorizationRequestStateRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"\x94\x01\n" +
	"$GetAuthorizationRequestStateResponse\x12l\n" +
	"\x1bauthorization_request_state\x18\x01 \x01(\v2,.proto.oidc.models.AuthorizationRequestStateR\x19authorizationRequestState\">\n" +
	"&DeleteAuthorizationRequestStateRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\")\n" +
	"'DeleteAuthorizationRequestStateResponse2\xe5\x03\n" +
	"\x1eAuthorizationRequestStateStore\x12\x95\x01\n" +
	"\x1eStoreAuthorizationRequestState\x127.proto.oidc.flows.StoreAuthorizationRequestStateRequest\x1a8.proto.oidc.flows.StoreAuthorizationRequestStateResponse\"\x00\x12\x8f\x01\n" +
	"\x1cGetAuthorizationRequestState\x125.proto.oidc.flows.GetAuthorizationRequestStateRequest\x1a6.proto.oidc.flows.GetAuthorizationRequestStateResponse\"\x00\x12\x98\x01\n" +
	"\x1fDeleteAuthorizationRequestState\x128.proto.oidc.flows.DeleteAuthorizationRequestStateRequest\x1a9.proto.oidc.flows.DeleteAuthorizationRequestStateResponse\"\x00B\x8d\x01\n" +
	"\x1ecom.fluffybunny.rageoidc.flowsP\x01ZGgithub.com/fluffy-bunny/fluffycore-rage-identity/proto/oidc/flows;flows\xaa\x02\x1fFluffyBunny.RageOidc.Oidc.Flowsb\x06proto3"

var (
	file_proto_oidc_flows_oidc_flow_proto_rawDescOnce sync.Once
	file_proto_oidc_flows_oidc_flow_proto_rawDescData []byte
)

func file_proto_oidc_flows_oidc_flow_proto_rawDescGZIP() []byte {
	file_proto_oidc_flows_oidc_flow_proto_rawDescOnce.Do(func() {
		file_proto_oidc_flows_oidc_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oidc_flows_oidc_flow_proto_rawDesc), len(file_proto_oidc_flows_oidc_flow_proto_rawDesc)))
	})
	return file_proto_oidc_flows_oidc_flow_proto_rawDescData
}

var file_proto_oidc_flows_oidc_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_oidc_flows_oidc_flow_proto_goTypes = []any{
	(*StoreAuthorizationRequestStateRequest)(nil),   // 0: proto.oidc.flows.StoreAuthorizationRequestStateRequest
	(*StoreAuthorizationRequestStateResponse)(nil),  // 1: proto.oidc.flows.StoreAuthorizationRequestStateResponse
	(*GetAuthorizationRequestStateRequest)(nil),     // 2: proto.oidc.flows.GetAuthorizationRequestStateRequest
	(*GetAuthorizationRequestStateResponse)(nil),    // 3: proto.oidc.flows.GetAuthorizationRequestStateResponse
	(*DeleteAuthorizationRequestStateRequest)(nil),  // 4: proto.oidc.flows.DeleteAuthorizationRequestStateRequest
	(*DeleteAuthorizationRequestStateResponse)(nil), // 5: proto.oidc.flows.DeleteAuthorizationRequestStateResponse
	(*models.AuthorizationRequestState)(nil),        // 6: proto.oidc.models.AuthorizationRequestState
}
var file_proto_oidc_flows_oidc_flow_proto_depIdxs = []int32{
	6, // 0: proto.oidc.flows.StoreAuthorizationRequestStateRequest.authorization_request_state:type_name -> proto.oidc.models.AuthorizationRequestState
	6, // 1: proto.oidc.flows.GetAuthorizationRequestStateResponse.authorization_request_state:type_name -> proto.oidc.models.AuthorizationRequestState
	0, // 2: proto.oidc.flows.AuthorizationRequestStateStore.StoreAuthorizationRequestState:input_type -> proto.oidc.flows.StoreAuthorizationRequestStateRequest
	2, // 3: proto.oidc.flows.AuthorizationRequestStateStore.GetAuthorizationRequestState:input_type -> proto.oidc.flows.GetAuthorizationRequestStateRequest
	4, // 4: proto.oidc.flows.AuthorizationRequestStateStore.DeleteAuthorizationRequestState:input_type -> proto.oidc.flows.DeleteAuthorizationRequestStateRequest
	1, // 5: proto.oidc.flows.AuthorizationRequestStateStore.StoreAuthorizationRequestState:output_type -> proto.oidc.flows.StoreAuthorizationRequestStateResponse
	3, // 6: proto.oidc.flows.AuthorizationRequestStateStore.GetAuthorizationRequestState:output_type -> proto.oidc.flows.GetAuthorizationRequestStateResponse
	5, // 7: proto.oidc.flows.AuthorizationRequestStateStore.DeleteAuthorizationRequestState:output_type -> proto.oidc.flows.DeleteAuthorizationRequestStateResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_oidc_flows_oidc_flow_proto_init() }
func file_proto_oidc_flows_oidc_flow_proto_init() {
	if File_proto_oidc_flows_oidc_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oidc_flows_oidc_flow_proto_rawDesc), len(file_proto_oidc_flows_oidc_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_oidc_flows_oidc_flow_proto_goTypes,
		DependencyIndexes: file_proto_oidc_flows_oidc_flow_proto_depIdxs,
		MessageInfos:      file_proto_oidc_flows_oidc_flow_proto_msgTypes,
	}.Build()
	File_proto_oidc_flows_oidc_flow_proto = out.File
	file_proto_oidc_flows_oidc_flow_proto_goTypes = nil
	file_proto_oidc_flows_oidc_flow_proto_depIdxs = nil
}
