// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/types/pagination.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order int32

const (
	// Conventional default for enums. Do not use this.
	Order_ORDER_UNSPECIFIED Order = 0
	// Ascending order
	Order_ASC Order = 1
	// Descending order
	Order_DESC Order = 2
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ORDER_UNSPECIFIED",
		1: "ASC",
		2: "DESC",
	}
	Order_value = map[string]int32{
		"ORDER_UNSPECIFIED": 0,
		"ASC":               1,
		"DESC":              2,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_pagination_proto_enumTypes[0].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_proto_types_pagination_proto_enumTypes[0]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_pagination_proto_rawDescGZIP(), []int{0}
}

type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of entries to retrieve
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Iterator      string `protobuf:"bytes,2,opt,name=iterator,proto3" json:"iterator,omitempty"`
	Order         Order  `protobuf:"varint,3,opt,name=order,proto3,enum=proto.types.Order" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_types_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_types_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetIterator() string {
	if x != nil {
		return x.Iterator
	}
	return ""
}

func (x *Pagination) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ORDER_UNSPECIFIED
}

// PaginationResponse ...
type PaginationResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Iterator     string                 `protobuf:"bytes,1,opt,name=iterator,proto3" json:"iterator,omitempty"`
	PrevIterator string                 `protobuf:"bytes,2,opt,name=prev_iterator,json=prevIterator,proto3" json:"prev_iterator,omitempty"`
	// Is a total count of records available?
	TotalAvailable bool `protobuf:"varint,3,opt,name=total_available,json=totalAvailable,proto3" json:"total_available,omitempty"`
	// Total number of records available (if totalAvailable = true)
	Total uint64 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	// There is no more data
	NoMoreData    bool `protobuf:"varint,5,opt,name=no_more_data,json=noMoreData,proto3" json:"no_more_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_proto_types_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_proto_types_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetIterator() string {
	if x != nil {
		return x.Iterator
	}
	return ""
}

func (x *PaginationResponse) GetPrevIterator() string {
	if x != nil {
		return x.PrevIterator
	}
	return ""
}

func (x *PaginationResponse) GetTotalAvailable() bool {
	if x != nil {
		return x.TotalAvailable
	}
	return false
}

func (x *PaginationResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetNoMoreData() bool {
	if x != nil {
		return x.NoMoreData
	}
	return false
}

var File_proto_types_pagination_proto protoreflect.FileDescriptor

const file_proto_types_pagination_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/types/pagination.proto\x12\vproto.types\x1a google/protobuf/descriptor.proto\"h\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x1a\n" +
	"\biterator\x18\x02 \x01(\tR\biterator\x12(\n" +
	"\x05order\x18\x03 \x01(\x0e2\x12.proto.types.OrderR\x05order\"\xb6\x01\n" +
	"\x12PaginationResponse\x12\x1a\n" +
	"\biterator\x18\x01 \x01(\tR\biterator\x12#\n" +
	"\rprev_iterator\x18\x02 \x01(\tR\fprevIterator\x12'\n" +
	"\x0ftotal_available\x18\x03 \x01(\bR\x0etotalAvailable\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x04R\x05total\x12 \n" +
	"\fno_more_data\x18\x05 \x01(\bR\n" +
	"noMoreData*1\n" +
	"\x05Order\x12\x15\n" +
	"\x11ORDER_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ASC\x10\x01\x12\b\n" +
	"\x04DESC\x10\x02B\x83\x01\n" +
	"\x1ecom.fluffybunny.rageoidc.typesP\x01ZBgithub.com/fluffy-bunny/fluffycore-rage-identity/proto/types;types\xaa\x02\x1aFluffyBunny.RageOidc.Typesb\x06proto3"

var (
	file_proto_types_pagination_proto_rawDescOnce sync.Once
	file_proto_types_pagination_proto_rawDescData []byte
)

func file_proto_types_pagination_proto_rawDescGZIP() []byte {
	file_proto_types_pagination_proto_rawDescOnce.Do(func() {
		file_proto_types_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_types_pagination_proto_rawDesc), len(file_proto_types_pagination_proto_rawDesc)))
	})
	return file_proto_types_pagination_proto_rawDescData
}

var file_proto_types_pagination_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_types_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_types_pagination_proto_goTypes = []any{
	(Order)(0),                 // 0: proto.types.Order
	(*Pagination)(nil),         // 1: proto.types.Pagination
	(*PaginationResponse)(nil), // 2: proto.types.PaginationResponse
}
var file_proto_types_pagination_proto_depIdxs = []int32{
	0, // 0: proto.types.Pagination.order:type_name -> proto.types.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_types_pagination_proto_init() }
func file_proto_types_pagination_proto_init() {
	if File_proto_types_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_types_pagination_proto_rawDesc), len(file_proto_types_pagination_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_pagination_proto_goTypes,
		DependencyIndexes: file_proto_types_pagination_proto_depIdxs,
		EnumInfos:         file_proto_types_pagination_proto_enumTypes,
		MessageInfos:      file_proto_types_pagination_proto_msgTypes,
	}.Build()
	File_proto_types_pagination_proto = out.File
	file_proto_types_pagination_proto_goTypes = nil
	file_proto_types_pagination_proto_depIdxs = nil
}
