// Code generated by protoc-gen-go-fluffycore-di. DO NOT EDIT.
// Code generated grpcGateway

package idp

import (
	context "context"
	fluffy_dozm_di "github.com/fluffy-bunny/fluffy-dozm-di"
	GRPCClientFactory "github.com/fluffy-bunny/fluffycore/contracts/GRPCClientFactory"
	endpoint "github.com/fluffy-bunny/fluffycore/contracts/endpoint"
	tokensource "github.com/fluffy-bunny/fluffycore/contracts/tokensource"
	grpcclient "github.com/fluffy-bunny/fluffycore/grpcclient"
	dicontext "github.com/fluffy-bunny/fluffycore/middleware/dicontext"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
	sync "sync"
)

// IAppIDPServiceClientAccessor defines the grpc client
type IAppIDPServiceClientAccessor interface {
	GetClient() (IDPServiceClient, error)
}

// AppIDPServiceClientAccessorConfig defines the grpc client struct
type AppIDPServiceClientAccessorConfig struct {
	Url string
}

// AppIDPServiceClientAccessor defines the grpc client struct
type AppIDPServiceClientAccessor struct {
	rwLock            sync.RWMutex
	config            *AppIDPServiceClientAccessorConfig
	appTokenSource    tokensource.IAppTokenSource
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory
	client            IDPServiceClient
}

var stemAppIDPServiceClientAccessor = (*AppIDPServiceClientAccessor)(nil)
var _ IAppIDPServiceClientAccessor = stemAppIDPServiceClientAccessor

func (s *AppIDPServiceClientAccessor) Ctor(
	config *AppIDPServiceClientAccessorConfig,
	appTokenSource tokensource.IAppTokenSource,
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory,
) (IAppIDPServiceClientAccessor, error) {
	return &AppIDPServiceClientAccessor{
		config:            config,
		appTokenSource:    appTokenSource,
		grpcClientFactory: grpcClientFactory,
	}, nil
}

// AddSingletonIAppIDPServiceClientAccessor ...
func AddSingletonIAppIDPServiceClientAccessor(
	cb fluffy_dozm_di.ContainerBuilder,
	config *AppIDPServiceClientAccessorConfig,
) {
	fluffy_dozm_di.AddInstance[*AppIDPServiceClientAccessorConfig](cb, config)
	fluffy_dozm_di.AddSingleton[IAppIDPServiceClientAccessor](cb, stemAppIDPServiceClientAccessor.Ctor)
}

func (s *AppIDPServiceClientAccessor) GetClient() (IDPServiceClient, error) {
	doGetClient := func() IDPServiceClient {
		s.rwLock.RLock()
		defer s.rwLock.RUnlock()
		if s.client != nil {
			return s.client
		}
		return nil
	}

	client := doGetClient()
	if client != nil {
		return client, nil
	}

	tokenSource, err := s.appTokenSource.GetTokenSource()
	if err != nil {
		return nil, err
	}
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--
	s.rwLock.Lock()
	defer s.rwLock.Unlock()
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--

	grpcClient, err := s.grpcClientFactory.NewGrpcClient(
		grpcclient.WithTarget(s.config.Url),
		grpcclient.WithTokenSource(tokenSource),
		grpcclient.WithInsecure(true), // TODO: remove this in production
	)
	if err != nil {
		return nil, err
	}
	s.client = NewIDPServiceClient(grpcClient.GetConnection())
	return s.client, nil
}

// IFluffyCoreIDPServiceServer defines the grpc server
type IFluffyCoreIDPServiceServer interface {
	IDPServiceServer
}

type UnimplementedFluffyCoreIDPServiceServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreIDPServiceServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// IDPServiceFluffyCoreServer defines the grpc server truct
type IDPServiceFluffyCoreServer struct {
	UnimplementedIDPServiceServer
	UnimplementedFluffyCoreIDPServiceServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *IDPServiceFluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterIDPServiceServer(s, srv)
}

// AddIDPServiceServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddIDPServiceServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreIDPServiceServer](cb, ctor)
}

// AddIDPServiceServer adds the fluffycore aware grpc server
func AddIDPServiceServer(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddIDPServiceServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &IDPServiceFluffyCoreServer{}
	})
}

// CreateIDP...
func (s *IDPServiceFluffyCoreServer) CreateIDP(ctx context.Context, request *CreateIDPRequest) (*CreateIDPResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreIDPServiceServer](requestContainer)
	return downstreamService.CreateIDP(ctx, request)
}

// GetIDP...
func (s *IDPServiceFluffyCoreServer) GetIDP(ctx context.Context, request *GetIDPRequest) (*GetIDPResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreIDPServiceServer](requestContainer)
	return downstreamService.GetIDP(ctx, request)
}

// GetIDPBySlug...
func (s *IDPServiceFluffyCoreServer) GetIDPBySlug(ctx context.Context, request *GetIDPBySlugRequest) (*GetIDPBySlugResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreIDPServiceServer](requestContainer)
	return downstreamService.GetIDPBySlug(ctx, request)
}

// DeleteIDP...
func (s *IDPServiceFluffyCoreServer) DeleteIDP(ctx context.Context, request *DeleteIDPRequest) (*DeleteIDPResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreIDPServiceServer](requestContainer)
	return downstreamService.DeleteIDP(ctx, request)
}

// UpdateIDP...
func (s *IDPServiceFluffyCoreServer) UpdateIDP(ctx context.Context, request *UpdateIDPRequest) (*UpdateIDPResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreIDPServiceServer](requestContainer)
	return downstreamService.UpdateIDP(ctx, request)
}

// ListIDP...
func (s *IDPServiceFluffyCoreServer) ListIDP(ctx context.Context, request *ListIDPRequest) (*ListIDPResponse, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreIDPServiceServer](requestContainer)
	return downstreamService.ListIDP(ctx, request)
}
