// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: proto/oidc/idp/idp.proto

package idp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SingletonIDPService_ListIDP_FullMethodName = "/proto.oidc.idp.SingletonIDPService/ListIDP"
)

// SingletonIDPServiceClient is the client API for SingletonIDPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SingletonIDPService ...
type SingletonIDPServiceClient interface {
	// List idps
	ListIDP(ctx context.Context, in *ListIDPRequest, opts ...grpc.CallOption) (*ListIDPResponse, error)
}

type singletonIDPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSingletonIDPServiceClient(cc grpc.ClientConnInterface) SingletonIDPServiceClient {
	return &singletonIDPServiceClient{cc}
}

func (c *singletonIDPServiceClient) ListIDP(ctx context.Context, in *ListIDPRequest, opts ...grpc.CallOption) (*ListIDPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIDPResponse)
	err := c.cc.Invoke(ctx, SingletonIDPService_ListIDP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SingletonIDPServiceServer is the server API for SingletonIDPService service.
// All implementations must embed UnimplementedSingletonIDPServiceServer
// for forward compatibility.
//
// SingletonIDPService ...
type SingletonIDPServiceServer interface {
	// List idps
	ListIDP(context.Context, *ListIDPRequest) (*ListIDPResponse, error)
	mustEmbedUnimplementedSingletonIDPServiceServer()
}

// UnimplementedSingletonIDPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSingletonIDPServiceServer struct{}

func (UnimplementedSingletonIDPServiceServer) ListIDP(context.Context, *ListIDPRequest) (*ListIDPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIDP not implemented")
}
func (UnimplementedSingletonIDPServiceServer) mustEmbedUnimplementedSingletonIDPServiceServer() {}
func (UnimplementedSingletonIDPServiceServer) testEmbeddedByValue()                             {}

// UnsafeSingletonIDPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SingletonIDPServiceServer will
// result in compilation errors.
type UnsafeSingletonIDPServiceServer interface {
	mustEmbedUnimplementedSingletonIDPServiceServer()
}

func RegisterSingletonIDPServiceServer(s grpc.ServiceRegistrar, srv SingletonIDPServiceServer) {
	// If the following call pancis, it indicates UnimplementedSingletonIDPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SingletonIDPService_ServiceDesc, srv)
}

func _SingletonIDPService_ListIDP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIDPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SingletonIDPServiceServer).ListIDP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SingletonIDPService_ListIDP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SingletonIDPServiceServer).ListIDP(ctx, req.(*ListIDPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SingletonIDPService_ServiceDesc is the grpc.ServiceDesc for SingletonIDPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SingletonIDPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.oidc.idp.SingletonIDPService",
	HandlerType: (*SingletonIDPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIDP",
			Handler:    _SingletonIDPService_ListIDP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oidc/idp/idp.proto",
}
