package main

import (
	"fmt"

	_ "github.com/fluffy-bunny/fluffycore-rage-identity/cmd/server/docs" // docs is generated by Swag CLI, you have to import it.
	example_runtime "github.com/fluffy-bunny/fluffycore-rage-identity/example/runtime"
	pkg_version "github.com/fluffy-bunny/fluffycore-rage-identity/example/version"
	fluffycore_cobracore_cmd "github.com/fluffy-bunny/fluffycore/cobracore/cmd"
)

// https://github.com/swaggo/echo-swagger

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:9044
// @BasePath /
// @securityDefinitions.basic BasicAuth

func main() {
	/*
		processDirectory, err := filepath.Abs(filepath.Dir(os.Args[0]))
		if err != nil {
			panic(err)
		}

	*/
	startup := example_runtime.NewStartup()
	fmt.Printf("Version: %s\n", pkg_version.Version())
	fluffycore_cobracore_cmd.SetVersion(pkg_version.Version())
	fluffycore_cobracore_cmd.Execute(startup)
}
